// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"context"
	"word_app/backend/src/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, u *domain.User, ext *domain.ExternalAuth) error {
	ret := _mock.Called(ctx, u, ext)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User, *domain.ExternalAuth) error); ok {
		r0 = returnFunc(ctx, u, ext)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - u *domain.User
//   - ext *domain.ExternalAuth
func (_e *MockRepository_Expecter) Create(ctx interface{}, u interface{}, ext interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, u, ext)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, u *domain.User, ext *domain.ExternalAuth)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		var arg2 *domain.ExternalAuth
		if args[2] != nil {
			arg2 = args[2].(*domain.ExternalAuth)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, u *domain.User, ext *domain.ExternalAuth) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByID(ctx context.Context, id int) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(ctx context.Context, id int)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(user *domain.User, err error) *MockRepository_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*domain.User, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByProvider provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByProvider(ctx context.Context, provider string, sub string) (*domain.User, error) {
	ret := _mock.Called(ctx, provider, sub)

	if len(ret) == 0 {
		panic("no return value specified for FindByProvider")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return returnFunc(ctx, provider, sub)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = returnFunc(ctx, provider, sub)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, provider, sub)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByProvider'
type MockRepository_FindByProvider_Call struct {
	*mock.Call
}

// FindByProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - sub string
func (_e *MockRepository_Expecter) FindByProvider(ctx interface{}, provider interface{}, sub interface{}) *MockRepository_FindByProvider_Call {
	return &MockRepository_FindByProvider_Call{Call: _e.mock.On("FindByProvider", ctx, provider, sub)}
}

func (_c *MockRepository_FindByProvider_Call) Run(run func(ctx context.Context, provider string, sub string)) *MockRepository_FindByProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_FindByProvider_Call) Return(user *domain.User, err error) *MockRepository_FindByProvider_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_FindByProvider_Call) RunAndReturn(run func(ctx context.Context, provider string, sub string) (*domain.User, error)) *MockRepository_FindByProvider_Call {
	_c.Call.Return(run)
	return _c
}

// IsRoot provides a mock function for the type MockRepository
func (_mock *MockRepository) IsRoot(ctx context.Context, userID int) (bool, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsRoot")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (bool, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_IsRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRoot'
type MockRepository_IsRoot_Call struct {
	*mock.Call
}

// IsRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockRepository_Expecter) IsRoot(ctx interface{}, userID interface{}) *MockRepository_IsRoot_Call {
	return &MockRepository_IsRoot_Call{Call: _e.mock.On("IsRoot", ctx, userID)}
}

func (_c *MockRepository_IsRoot_Call) Run(run func(ctx context.Context, userID int)) *MockRepository_IsRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_IsRoot_Call) Return(b bool, err error) *MockRepository_IsRoot_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_IsRoot_Call) RunAndReturn(run func(ctx context.Context, userID int) (bool, error)) *MockRepository_IsRoot_Call {
	_c.Call.Return(run)
	return _c
}
