// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldIsAdmin holds the string denoting the isadmin field in the database.
	FieldIsAdmin = "is_admin"
	// FieldIsRoot holds the string denoting the isroot field in the database.
	FieldIsRoot = "is_root"
	// FieldIsTest holds the string denoting the istest field in the database.
	FieldIsTest = "is_test"
	// EdgeRegisteredWords holds the string denoting the registered_words edge name in mutations.
	EdgeRegisteredWords = "registered_words"
	// EdgeQuizs holds the string denoting the quizs edge name in mutations.
	EdgeQuizs = "quizs"
	// EdgeUserConfig holds the string denoting the user_config edge name in mutations.
	EdgeUserConfig = "user_config"
	// EdgeExternalAuths holds the string denoting the external_auths edge name in mutations.
	EdgeExternalAuths = "external_auths"
	// EdgeUserDailyUsage holds the string denoting the user_daily_usage edge name in mutations.
	EdgeUserDailyUsage = "user_daily_usage"
	// Table holds the table name of the user in the database.
	Table = "users"
	// RegisteredWordsTable is the table that holds the registered_words relation/edge.
	RegisteredWordsTable = "registered_words"
	// RegisteredWordsInverseTable is the table name for the RegisteredWord entity.
	// It exists in this package in order to avoid circular dependency with the "registeredword" package.
	RegisteredWordsInverseTable = "registered_words"
	// RegisteredWordsColumn is the table column denoting the registered_words relation/edge.
	RegisteredWordsColumn = "user_id"
	// QuizsTable is the table that holds the quizs relation/edge.
	QuizsTable = "quizs"
	// QuizsInverseTable is the table name for the Quiz entity.
	// It exists in this package in order to avoid circular dependency with the "quiz" package.
	QuizsInverseTable = "quizs"
	// QuizsColumn is the table column denoting the quizs relation/edge.
	QuizsColumn = "user_id"
	// UserConfigTable is the table that holds the user_config relation/edge.
	UserConfigTable = "user_configs"
	// UserConfigInverseTable is the table name for the UserConfig entity.
	// It exists in this package in order to avoid circular dependency with the "userconfig" package.
	UserConfigInverseTable = "user_configs"
	// UserConfigColumn is the table column denoting the user_config relation/edge.
	UserConfigColumn = "user_id"
	// ExternalAuthsTable is the table that holds the external_auths relation/edge.
	ExternalAuthsTable = "external_auths"
	// ExternalAuthsInverseTable is the table name for the ExternalAuth entity.
	// It exists in this package in order to avoid circular dependency with the "externalauth" package.
	ExternalAuthsInverseTable = "external_auths"
	// ExternalAuthsColumn is the table column denoting the external_auths relation/edge.
	ExternalAuthsColumn = "user_external_auths"
	// UserDailyUsageTable is the table that holds the user_daily_usage relation/edge.
	UserDailyUsageTable = "user_daily_usages"
	// UserDailyUsageInverseTable is the table name for the UserDailyUsage entity.
	// It exists in this package in order to avoid circular dependency with the "userdailyusage" package.
	UserDailyUsageInverseTable = "user_daily_usages"
	// UserDailyUsageColumn is the table column denoting the user_daily_usage relation/edge.
	UserDailyUsageColumn = "user_user_daily_usage"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldPassword,
	FieldName,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldIsAdmin,
	FieldIsRoot,
	FieldIsTest,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultIsAdmin holds the default value on creation for the "isAdmin" field.
	DefaultIsAdmin bool
	// DefaultIsRoot holds the default value on creation for the "isRoot" field.
	DefaultIsRoot bool
	// DefaultIsTest holds the default value on creation for the "isTest" field.
	DefaultIsTest bool
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByIsAdmin orders the results by the isAdmin field.
func ByIsAdmin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsAdmin, opts...).ToFunc()
}

// ByIsRoot orders the results by the isRoot field.
func ByIsRoot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsRoot, opts...).ToFunc()
}

// ByIsTest orders the results by the isTest field.
func ByIsTest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsTest, opts...).ToFunc()
}

// ByRegisteredWordsCount orders the results by registered_words count.
func ByRegisteredWordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRegisteredWordsStep(), opts...)
	}
}

// ByRegisteredWords orders the results by registered_words terms.
func ByRegisteredWords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRegisteredWordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByQuizsCount orders the results by quizs count.
func ByQuizsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newQuizsStep(), opts...)
	}
}

// ByQuizs orders the results by quizs terms.
func ByQuizs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuizsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserConfigField orders the results by user_config field.
func ByUserConfigField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserConfigStep(), sql.OrderByField(field, opts...))
	}
}

// ByExternalAuthsCount orders the results by external_auths count.
func ByExternalAuthsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newExternalAuthsStep(), opts...)
	}
}

// ByExternalAuths orders the results by external_auths terms.
func ByExternalAuths(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExternalAuthsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserDailyUsageField orders the results by user_daily_usage field.
func ByUserDailyUsageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserDailyUsageStep(), sql.OrderByField(field, opts...))
	}
}
func newRegisteredWordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RegisteredWordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RegisteredWordsTable, RegisteredWordsColumn),
	)
}
func newQuizsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuizsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, QuizsTable, QuizsColumn),
	)
}
func newUserConfigStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserConfigInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, UserConfigTable, UserConfigColumn),
	)
}
func newExternalAuthsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExternalAuthsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ExternalAuthsTable, ExternalAuthsColumn),
	)
}
func newUserDailyUsageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserDailyUsageInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, UserDailyUsageTable, UserDailyUsageColumn),
	)
}
