// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"
	"time"

	"word_app/backend/src/utils/tempjwt"

	"github.com/coreos/go-oidc/v3/oidc"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// AuthURL provides a mock function for the type MockProvider
func (_mock *MockProvider) AuthURL(state string, nonce string) string {
	ret := _mock.Called(state, nonce)

	if len(ret) == 0 {
		panic("no return value specified for AuthURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(state, nonce)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProvider_AuthURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthURL'
type MockProvider_AuthURL_Call struct {
	*mock.Call
}

// AuthURL is a helper method to define mock.On call
//   - state string
//   - nonce string
func (_e *MockProvider_Expecter) AuthURL(state interface{}, nonce interface{}) *MockProvider_AuthURL_Call {
	return &MockProvider_AuthURL_Call{Call: _e.mock.On("AuthURL", state, nonce)}
}

func (_c *MockProvider_AuthURL_Call) Run(run func(state string, nonce string)) *MockProvider_AuthURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_AuthURL_Call) Return(s string) *MockProvider_AuthURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProvider_AuthURL_Call) RunAndReturn(run func(state string, nonce string) string) *MockProvider_AuthURL_Call {
	_c.Call.Return(run)
	return _c
}

// Exchange provides a mock function for the type MockProvider
func (_mock *MockProvider) Exchange(ctx context.Context, code string) (*tempjwt.Identity, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 *tempjwt.Identity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*tempjwt.Identity, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *tempjwt.Identity); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tempjwt.Identity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type MockProvider_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockProvider_Expecter) Exchange(ctx interface{}, code interface{}) *MockProvider_Exchange_Call {
	return &MockProvider_Exchange_Call{Call: _e.mock.On("Exchange", ctx, code)}
}

func (_c *MockProvider_Exchange_Call) Run(run func(ctx context.Context, code string)) *MockProvider_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_Exchange_Call) Return(identity *tempjwt.Identity, err error) *MockProvider_Exchange_Call {
	_c.Call.Return(identity, err)
	return _c
}

func (_c *MockProvider_Exchange_Call) RunAndReturn(run func(ctx context.Context, code string) (*tempjwt.Identity, error)) *MockProvider_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateNonce provides a mock function for the type MockProvider
func (_mock *MockProvider) ValidateNonce(idTok *oidc.IDToken, expected string) error {
	ret := _mock.Called(idTok, expected)

	if len(ret) == 0 {
		panic("no return value specified for ValidateNonce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*oidc.IDToken, string) error); ok {
		r0 = returnFunc(idTok, expected)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProvider_ValidateNonce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateNonce'
type MockProvider_ValidateNonce_Call struct {
	*mock.Call
}

// ValidateNonce is a helper method to define mock.On call
//   - idTok *oidc.IDToken
//   - expected string
func (_e *MockProvider_Expecter) ValidateNonce(idTok interface{}, expected interface{}) *MockProvider_ValidateNonce_Call {
	return &MockProvider_ValidateNonce_Call{Call: _e.mock.On("ValidateNonce", idTok, expected)}
}

func (_c *MockProvider_ValidateNonce_Call) Run(run func(idTok *oidc.IDToken, expected string)) *MockProvider_ValidateNonce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *oidc.IDToken
		if args[0] != nil {
			arg0 = args[0].(*oidc.IDToken)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_ValidateNonce_Call) Return(err error) *MockProvider_ValidateNonce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProvider_ValidateNonce_Call) RunAndReturn(run func(idTok *oidc.IDToken, expected string) error) *MockProvider_ValidateNonce_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTempTokenGenerator creates a new instance of MockTempTokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTempTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTempTokenGenerator {
	mock := &MockTempTokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTempTokenGenerator is an autogenerated mock type for the TempTokenGenerator type
type MockTempTokenGenerator struct {
	mock.Mock
}

type MockTempTokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTempTokenGenerator) EXPECT() *MockTempTokenGenerator_Expecter {
	return &MockTempTokenGenerator_Expecter{mock: &_m.Mock}
}

// GenerateTemp provides a mock function for the type MockTempTokenGenerator
func (_mock *MockTempTokenGenerator) GenerateTemp(id *tempjwt.Identity, ttl time.Duration) (string, error) {
	ret := _mock.Called(id, ttl)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTemp")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*tempjwt.Identity, time.Duration) (string, error)); ok {
		return returnFunc(id, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(*tempjwt.Identity, time.Duration) string); ok {
		r0 = returnFunc(id, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*tempjwt.Identity, time.Duration) error); ok {
		r1 = returnFunc(id, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTempTokenGenerator_GenerateTemp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTemp'
type MockTempTokenGenerator_GenerateTemp_Call struct {
	*mock.Call
}

// GenerateTemp is a helper method to define mock.On call
//   - id *tempjwt.Identity
//   - ttl time.Duration
func (_e *MockTempTokenGenerator_Expecter) GenerateTemp(id interface{}, ttl interface{}) *MockTempTokenGenerator_GenerateTemp_Call {
	return &MockTempTokenGenerator_GenerateTemp_Call{Call: _e.mock.On("GenerateTemp", id, ttl)}
}

func (_c *MockTempTokenGenerator_GenerateTemp_Call) Run(run func(id *tempjwt.Identity, ttl time.Duration)) *MockTempTokenGenerator_GenerateTemp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *tempjwt.Identity
		if args[0] != nil {
			arg0 = args[0].(*tempjwt.Identity)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTempTokenGenerator_GenerateTemp_Call) Return(s string, err error) *MockTempTokenGenerator_GenerateTemp_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTempTokenGenerator_GenerateTemp_Call) RunAndReturn(run func(id *tempjwt.Identity, ttl time.Duration) (string, error)) *MockTempTokenGenerator_GenerateTemp_Call {
	_c.Call.Return(run)
	return _c
}

// ParseTemp provides a mock function for the type MockTempTokenGenerator
func (_mock *MockTempTokenGenerator) ParseTemp(tok string) (*tempjwt.Identity, error) {
	ret := _mock.Called(tok)

	if len(ret) == 0 {
		panic("no return value specified for ParseTemp")
	}

	var r0 *tempjwt.Identity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*tempjwt.Identity, error)); ok {
		return returnFunc(tok)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *tempjwt.Identity); ok {
		r0 = returnFunc(tok)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tempjwt.Identity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tok)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTempTokenGenerator_ParseTemp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseTemp'
type MockTempTokenGenerator_ParseTemp_Call struct {
	*mock.Call
}

// ParseTemp is a helper method to define mock.On call
//   - tok string
func (_e *MockTempTokenGenerator_Expecter) ParseTemp(tok interface{}) *MockTempTokenGenerator_ParseTemp_Call {
	return &MockTempTokenGenerator_ParseTemp_Call{Call: _e.mock.On("ParseTemp", tok)}
}

func (_c *MockTempTokenGenerator_ParseTemp_Call) Run(run func(tok string)) *MockTempTokenGenerator_ParseTemp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTempTokenGenerator_ParseTemp_Call) Return(identity *tempjwt.Identity, err error) *MockTempTokenGenerator_ParseTemp_Call {
	_c.Call.Return(identity, err)
	return _c
}

func (_c *MockTempTokenGenerator_ParseTemp_Call) RunAndReturn(run func(tok string) (*tempjwt.Identity, error)) *MockTempTokenGenerator_ParseTemp_Call {
	_c.Call.Return(run)
	return _c
}
