// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	"word_app/backend/src/usecase/auth"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUsecase creates a new instance of MockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecase {
	mock := &MockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

type MockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecase) EXPECT() *MockUsecase_Expecter {
	return &MockUsecase_Expecter{mock: &_m.Mock}
}

// CompleteSignUp provides a mock function for the type MockUsecase
func (_mock *MockUsecase) CompleteSignUp(ctx context.Context, tempToken string, pass *string) (string, error) {
	ret := _mock.Called(ctx, tempToken, pass)

	if len(ret) == 0 {
		panic("no return value specified for CompleteSignUp")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string) (string, error)); ok {
		return returnFunc(ctx, tempToken, pass)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string) string); ok {
		r0 = returnFunc(ctx, tempToken, pass)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string) error); ok {
		r1 = returnFunc(ctx, tempToken, pass)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_CompleteSignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteSignUp'
type MockUsecase_CompleteSignUp_Call struct {
	*mock.Call
}

// CompleteSignUp is a helper method to define mock.On call
//   - ctx context.Context
//   - tempToken string
//   - pass *string
func (_e *MockUsecase_Expecter) CompleteSignUp(ctx interface{}, tempToken interface{}, pass interface{}) *MockUsecase_CompleteSignUp_Call {
	return &MockUsecase_CompleteSignUp_Call{Call: _e.mock.On("CompleteSignUp", ctx, tempToken, pass)}
}

func (_c *MockUsecase_CompleteSignUp_Call) Run(run func(ctx context.Context, tempToken string, pass *string)) *MockUsecase_CompleteSignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsecase_CompleteSignUp_Call) Return(s string, err error) *MockUsecase_CompleteSignUp_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUsecase_CompleteSignUp_Call) RunAndReturn(run func(ctx context.Context, tempToken string, pass *string) (string, error)) *MockUsecase_CompleteSignUp_Call {
	_c.Call.Return(run)
	return _c
}

// HandleCallback provides a mock function for the type MockUsecase
func (_mock *MockUsecase) HandleCallback(ctx context.Context, code string) (*auth.CallbackResult, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for HandleCallback")
	}

	var r0 *auth.CallbackResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*auth.CallbackResult, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *auth.CallbackResult); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.CallbackResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_HandleCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCallback'
type MockUsecase_HandleCallback_Call struct {
	*mock.Call
}

// HandleCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockUsecase_Expecter) HandleCallback(ctx interface{}, code interface{}) *MockUsecase_HandleCallback_Call {
	return &MockUsecase_HandleCallback_Call{Call: _e.mock.On("HandleCallback", ctx, code)}
}

func (_c *MockUsecase_HandleCallback_Call) Run(run func(ctx context.Context, code string)) *MockUsecase_HandleCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_HandleCallback_Call) Return(callbackResult *auth.CallbackResult, err error) *MockUsecase_HandleCallback_Call {
	_c.Call.Return(callbackResult, err)
	return _c
}

func (_c *MockUsecase_HandleCallback_Call) RunAndReturn(run func(ctx context.Context, code string) (*auth.CallbackResult, error)) *MockUsecase_HandleCallback_Call {
	_c.Call.Return(run)
	return _c
}

// StartLogin provides a mock function for the type MockUsecase
func (_mock *MockUsecase) StartLogin(ctx context.Context, state string, nonce string) string {
	ret := _mock.Called(ctx, state, nonce)

	if len(ret) == 0 {
		panic("no return value specified for StartLogin")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, state, nonce)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUsecase_StartLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartLogin'
type MockUsecase_StartLogin_Call struct {
	*mock.Call
}

// StartLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
//   - nonce string
func (_e *MockUsecase_Expecter) StartLogin(ctx interface{}, state interface{}, nonce interface{}) *MockUsecase_StartLogin_Call {
	return &MockUsecase_StartLogin_Call{Call: _e.mock.On("StartLogin", ctx, state, nonce)}
}

func (_c *MockUsecase_StartLogin_Call) Run(run func(ctx context.Context, state string, nonce string)) *MockUsecase_StartLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsecase_StartLogin_Call) Return(s string) *MockUsecase_StartLogin_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUsecase_StartLogin_Call) RunAndReturn(run func(ctx context.Context, state string, nonce string) string) *MockUsecase_StartLogin_Call {
	_c.Call.Return(run)
	return _c
}

// TestLoginWithRateLimit provides a mock function for the type MockUsecase
func (_mock *MockUsecase) TestLoginWithRateLimit(ctx context.Context, ip string, uaHash string, route string, jump string) (*auth.TestLoginOutput, []byte, int, error) {
	ret := _mock.Called(ctx, ip, uaHash, route, jump)

	if len(ret) == 0 {
		panic("no return value specified for TestLoginWithRateLimit")
	}

	var r0 *auth.TestLoginOutput
	var r1 []byte
	var r2 int
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*auth.TestLoginOutput, []byte, int, error)); ok {
		return returnFunc(ctx, ip, uaHash, route, jump)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *auth.TestLoginOutput); ok {
		r0 = returnFunc(ctx, ip, uaHash, route, jump)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.TestLoginOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) []byte); ok {
		r1 = returnFunc(ctx, ip, uaHash, route, jump)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, string) int); ok {
		r2 = returnFunc(ctx, ip, uaHash, route, jump)
	} else {
		r2 = ret.Get(2).(int)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, string, string, string, string) error); ok {
		r3 = returnFunc(ctx, ip, uaHash, route, jump)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockUsecase_TestLoginWithRateLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestLoginWithRateLimit'
type MockUsecase_TestLoginWithRateLimit_Call struct {
	*mock.Call
}

// TestLoginWithRateLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - ip string
//   - uaHash string
//   - route string
//   - jump string
func (_e *MockUsecase_Expecter) TestLoginWithRateLimit(ctx interface{}, ip interface{}, uaHash interface{}, route interface{}, jump interface{}) *MockUsecase_TestLoginWithRateLimit_Call {
	return &MockUsecase_TestLoginWithRateLimit_Call{Call: _e.mock.On("TestLoginWithRateLimit", ctx, ip, uaHash, route, jump)}
}

func (_c *MockUsecase_TestLoginWithRateLimit_Call) Run(run func(ctx context.Context, ip string, uaHash string, route string, jump string)) *MockUsecase_TestLoginWithRateLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUsecase_TestLoginWithRateLimit_Call) Return(testLoginOutput *auth.TestLoginOutput, bytes []byte, n int, err error) *MockUsecase_TestLoginWithRateLimit_Call {
	_c.Call.Return(testLoginOutput, bytes, n, err)
	return _c
}

func (_c *MockUsecase_TestLoginWithRateLimit_Call) RunAndReturn(run func(ctx context.Context, ip string, uaHash string, route string, jump string) (*auth.TestLoginOutput, []byte, int, error)) *MockUsecase_TestLoginWithRateLimit_Call {
	_c.Call.Return(run)
	return _c
}

// TestLogout provides a mock function for the type MockUsecase
func (_mock *MockUsecase) TestLogout(ctx context.Context, actorID int) error {
	ret := _mock.Called(ctx, actorID)

	if len(ret) == 0 {
		panic("no return value specified for TestLogout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, actorID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsecase_TestLogout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestLogout'
type MockUsecase_TestLogout_Call struct {
	*mock.Call
}

// TestLogout is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID int
func (_e *MockUsecase_Expecter) TestLogout(ctx interface{}, actorID interface{}) *MockUsecase_TestLogout_Call {
	return &MockUsecase_TestLogout_Call{Call: _e.mock.On("TestLogout", ctx, actorID)}
}

func (_c *MockUsecase_TestLogout_Call) Run(run func(ctx context.Context, actorID int)) *MockUsecase_TestLogout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_TestLogout_Call) Return(err error) *MockUsecase_TestLogout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsecase_TestLogout_Call) RunAndReturn(run func(ctx context.Context, actorID int) error) *MockUsecase_TestLogout_Call {
	_c.Call.Return(run)
	return _c
}
