# ベースイメージの指定
FROM node:22

# 作業ディレクトリの作成
WORKDIR /app

# 依存関係のインストール
COPY package.json package-lock.json ./
RUN npm install

# ソースコードのコピー
COPY . .

# 開発用の環境変数を設定
ENV CHOKIDAR_USEPOLLING=true

# 開発サーバーの起動
CMD ["npm", "run", "dev"]