version: 2

run:
  timeout: 5m

issues:
  exclude-dirs:
    - opt
    - go
    - ent
    - mocks
  exclude-files:
    - ^src/infrastructure/app_client\.go$

linters-settings:
  gocyclo:
    min-complexity: 15
  govet: {}

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gocyclo
    - revive
    # - goimports ← 削除
    # - shadow    ← 必要ならここで有効化

formatters:
  enable:
    - goimports
  goimports:
    local-prefixes: word_app/backend

output:
  format: colored-line-number
  sort-results: true
