run:
  timeout: 5m
issues:
  exclude-dirs:
    - "opt"
    - "go"
    - "ent"
    - "mocks"

linters-settings:
  goimports:
    local-prefixes: "word_app/backend"

  govet:
    check-shadowing: true
    enable:          # ← ここで shadow アナライザを有効化
      - shadow

  gocyclo:
    min-complexity: 15

linters:
  enable:
    - errcheck
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - gocyclo
    - revive

output:
  formats:
    colored-line-number
  sort-results: true
