run:
  timeout: 5m
  skip-dirs:
    - "opt"
    - "go"
    - "ent"
    - "mocks"

linters-settings:
  goimports:
    local-prefixes: "word_app/backend"

  govet:
    check-shadowing: true

  gocyclo:
    min-complexity: 15

linters:
  enable:
    - govet
    - errcheck
    - gofmt
    - goimports
    - staticcheck
    - gocyclo

output:
  formats:
    colored-line-number
  sort-results: true

issues:
  exclude-dirs:
    - "opt"
    - "go"
    - "ent"
    - "mocks"
