version: 2

run:
  timeout: 5m
issues:
  exclude-dirs:
    - opt
    - go
    - ent
    - mocks
  exclude-files:
    - ^src/infrastructure/app_client\.go$

linters-settings:
  gocyclo:
    min-complexity: 15
  # govet の個別設定が不要なら空 or 削除
  govet: {}

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gocyclo
    - revive

formatters:
  enable:
    - goimports
  goimports:
    local-prefixes: word_app/backend

output:
  format: colored-line-number
  sort-results: true
