dir: "{{.InterfaceDir}}"
filename: "{{.SrcPackageName}}_mock.go"
force-file-write: true
formatter: goimports
log-level: info
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
recursive: false
template: testify
template-schema: "{{.Template}}.schema.json"
all: true # パッケージ内すべての interface
packages:
  word_app/backend/src/handlers/auth:
    config:
      dir: src/mocks/http/auth
      recursive: false

  word_app/backend/src/handlers/setting:
    config:
      dir: src/mocks/http/setting
      recursive: false

  word_app/backend/src/handlers/user:
    config:
      dir: src/mocks/http/user
      recursive: false

  word_app/backend/src/middleware/jwt:
    config:
      dir: src/mocks/middleware/jwt
      recursive: false

  word_app/backend/src/infrastructure/auth/line:
    config:
      dir: src/mocks/infrastructure/auth/line
      recursive: false

  word_app/backend/src/infrastructure/jwt:
    config:
      dir: src/mocks/infrastructure/jwt
      recursive: false

  word_app/backend/src/infrastructure/repository/user:
    config:
      dir: src/mocks/infrastructure/repository/user
      recursive: false

  word_app/backend/src/infrastructure/repository/setting:
    config:
      dir: src/mocks/infrastructure/repository/setting
      recursive: false

  word_app/backend/src/infrastructure/repository/tx:
    config:
      dir: src/mocks/infrastructure/repository/tx
      recursive: false

  word_app/backend/src/infrastructure/repository/userdailyusage:
    config:
      dir: src/mocks/infrastructure/repository/userdailyusage
      recursive: false

  word_app/backend/src/usecase/auth:
    config:
      dir: src/mocks/usecase/auth
      recursive: false

  word_app/backend/src/usecase/jwt:
    config:
      dir: src/mocks/usecase/jwt
      recursive: false

  word_app/backend/src/usecase/setting:
    config:
      dir: src/mocks/usecase/setting
      recursive: false

  word_app/backend/src/usecase/user:
    config:
      dir: src/mocks/usecase/user
      recursive: false

  word_app/backend/src/interfaces/service_interfaces:
    config:
      dir: src/mocks/service_interfaces
      recursive: false
