dir: '{{.InterfaceDir}}'
filename: '{{.SrcPackageName}}_mock.go'
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
recursive: false
template: testify
template-schema: '{{.Template}}.schema.json'
all: true                            # パッケージ内すべての interface
packages:

  word_app/backend/src/interfaces/http/auth:
    config:
      dir: src/mocks/http/auth
      recursive: false

  word_app/backend/src/interfaces/http/middleware:
    config:
      dir: src/mocks/http/middleware
      recursive: false

  word_app/backend/src/interfaces/repository/auth:
    config:
      dir: src/mocks/repository/auth
      recursive: false

  word_app/backend/src/interfaces/repository/user:
    config:
      dir: src/mocks/repository/user
      recursive: false

  word_app/backend/src/interfaces/usecase/port/auth:
    config:
      dir: src/mocks/usecase/port/auth
      recursive: false

  word_app/backend/src/interfaces/service_interfaces:
    config:
      dir: src/mocks/service_interfaces
      recursive: false
