# ベースイメージとして最新のgolangを使用
FROM golang:latest

# 作業ディレクトリを設定
WORKDIR /app

# Goのモジュールをコピー
COPY go.mod go.sum ./
RUN go mod download

# アプリケーションのソースコードをコピー
COPY . .

# アプリケーションをビルド
RUN go build -o main .

# バックエンドのポートを設定
EXPOSE 8080

# アプリケーションを実行
CMD ["./main"]