// Code generated by ent, DO NOT EDIT.

package quizquestion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the quizquestion type in the database.
	Label = "quiz_question"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldQuizID holds the string denoting the quiz_id field in the database.
	FieldQuizID = "quiz_id"
	// FieldQuestionNumber holds the string denoting the question_number field in the database.
	FieldQuestionNumber = "question_number"
	// FieldWordID holds the string denoting the word_id field in the database.
	FieldWordID = "word_id"
	// FieldCorrectJpmID holds the string denoting the correct_jpm_id field in the database.
	FieldCorrectJpmID = "correct_jpm_id"
	// FieldChoicesJpmIds holds the string denoting the choices_jpm_ids field in the database.
	FieldChoicesJpmIds = "choices_jpm_ids"
	// FieldAnswerJpmID holds the string denoting the answer_jpm_id field in the database.
	FieldAnswerJpmID = "answer_jpm_id"
	// FieldIsCorrect holds the string denoting the is_correct field in the database.
	FieldIsCorrect = "is_correct"
	// FieldAnsweredAt holds the string denoting the answered_at field in the database.
	FieldAnsweredAt = "answered_at"
	// FieldTimeMs holds the string denoting the time_ms field in the database.
	FieldTimeMs = "time_ms"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// EdgeQuiz holds the string denoting the quiz edge name in mutations.
	EdgeQuiz = "quiz"
	// EdgeWord holds the string denoting the word edge name in mutations.
	EdgeWord = "word"
	// EdgeJapaneseMean holds the string denoting the japanese_mean edge name in mutations.
	EdgeJapaneseMean = "japanese_mean"
	// Table holds the table name of the quizquestion in the database.
	Table = "quiz_questions"
	// QuizTable is the table that holds the quiz relation/edge.
	QuizTable = "quiz_questions"
	// QuizInverseTable is the table name for the Quiz entity.
	// It exists in this package in order to avoid circular dependency with the "quiz" package.
	QuizInverseTable = "quizs"
	// QuizColumn is the table column denoting the quiz relation/edge.
	QuizColumn = "quiz_id"
	// WordTable is the table that holds the word relation/edge.
	WordTable = "quiz_questions"
	// WordInverseTable is the table name for the Word entity.
	// It exists in this package in order to avoid circular dependency with the "word" package.
	WordInverseTable = "words"
	// WordColumn is the table column denoting the word relation/edge.
	WordColumn = "word_id"
	// JapaneseMeanTable is the table that holds the japanese_mean relation/edge.
	JapaneseMeanTable = "quiz_questions"
	// JapaneseMeanInverseTable is the table name for the JapaneseMean entity.
	// It exists in this package in order to avoid circular dependency with the "japanesemean" package.
	JapaneseMeanInverseTable = "japanese_means"
	// JapaneseMeanColumn is the table column denoting the japanese_mean relation/edge.
	JapaneseMeanColumn = "correct_jpm_id"
)

// Columns holds all SQL columns for quizquestion fields.
var Columns = []string{
	FieldID,
	FieldQuizID,
	FieldQuestionNumber,
	FieldWordID,
	FieldCorrectJpmID,
	FieldChoicesJpmIds,
	FieldAnswerJpmID,
	FieldIsCorrect,
	FieldAnsweredAt,
	FieldTimeMs,
	FieldCreatedAt,
	FieldDeletedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "quiz_questions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"registered_word_quiz_questions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// WordIDValidator is a validator for the "word_id" field. It is called by the builders before save.
	WordIDValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the QuizQuestion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByQuizID orders the results by the quiz_id field.
func ByQuizID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuizID, opts...).ToFunc()
}

// ByQuestionNumber orders the results by the question_number field.
func ByQuestionNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuestionNumber, opts...).ToFunc()
}

// ByWordID orders the results by the word_id field.
func ByWordID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWordID, opts...).ToFunc()
}

// ByCorrectJpmID orders the results by the correct_jpm_id field.
func ByCorrectJpmID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCorrectJpmID, opts...).ToFunc()
}

// ByAnswerJpmID orders the results by the answer_jpm_id field.
func ByAnswerJpmID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnswerJpmID, opts...).ToFunc()
}

// ByIsCorrect orders the results by the is_correct field.
func ByIsCorrect(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsCorrect, opts...).ToFunc()
}

// ByAnsweredAt orders the results by the answered_at field.
func ByAnsweredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnsweredAt, opts...).ToFunc()
}

// ByTimeMs orders the results by the time_ms field.
func ByTimeMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeMs, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByQuizField orders the results by quiz field.
func ByQuizField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuizStep(), sql.OrderByField(field, opts...))
	}
}

// ByWordField orders the results by word field.
func ByWordField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWordStep(), sql.OrderByField(field, opts...))
	}
}

// ByJapaneseMeanField orders the results by japanese_mean field.
func ByJapaneseMeanField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJapaneseMeanStep(), sql.OrderByField(field, opts...))
	}
}
func newQuizStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuizInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, QuizTable, QuizColumn),
	)
}
func newWordStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WordInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WordTable, WordColumn),
	)
}
func newJapaneseMeanStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JapaneseMeanInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, JapaneseMeanTable, JapaneseMeanColumn),
	)
}
