// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ratelimit

import (
	"context"

	"word_app/backend/src/infrastructure/ratelimit"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRateLimiter creates a new instance of MockRateLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRateLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRateLimiter {
	mock := &MockRateLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRateLimiter is an autogenerated mock type for the RateLimiter type
type MockRateLimiter struct {
	mock.Mock
}

type MockRateLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRateLimiter) EXPECT() *MockRateLimiter_Expecter {
	return &MockRateLimiter_Expecter{mock: &_m.Mock}
}

// CheckRateLimit provides a mock function for the type MockRateLimiter
func (_mock *MockRateLimiter) CheckRateLimit(ctx context.Context, ip string, uaHash string, route string) (*ratelimit.RateLimitResult, error) {
	ret := _mock.Called(ctx, ip, uaHash, route)

	if len(ret) == 0 {
		panic("no return value specified for CheckRateLimit")
	}

	var r0 *ratelimit.RateLimitResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*ratelimit.RateLimitResult, error)); ok {
		return returnFunc(ctx, ip, uaHash, route)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *ratelimit.RateLimitResult); ok {
		r0 = returnFunc(ctx, ip, uaHash, route)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ratelimit.RateLimitResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, ip, uaHash, route)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRateLimiter_CheckRateLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckRateLimit'
type MockRateLimiter_CheckRateLimit_Call struct {
	*mock.Call
}

// CheckRateLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - ip string
//   - uaHash string
//   - route string
func (_e *MockRateLimiter_Expecter) CheckRateLimit(ctx interface{}, ip interface{}, uaHash interface{}, route interface{}) *MockRateLimiter_CheckRateLimit_Call {
	return &MockRateLimiter_CheckRateLimit_Call{Call: _e.mock.On("CheckRateLimit", ctx, ip, uaHash, route)}
}

func (_c *MockRateLimiter_CheckRateLimit_Call) Run(run func(ctx context.Context, ip string, uaHash string, route string)) *MockRateLimiter_CheckRateLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRateLimiter_CheckRateLimit_Call) Return(rateLimitResult *ratelimit.RateLimitResult, err error) *MockRateLimiter_CheckRateLimit_Call {
	_c.Call.Return(rateLimitResult, err)
	return _c
}

func (_c *MockRateLimiter_CheckRateLimit_Call) RunAndReturn(run func(ctx context.Context, ip string, uaHash string, route string) (*ratelimit.RateLimitResult, error)) *MockRateLimiter_CheckRateLimit_Call {
	_c.Call.Return(run)
	return _c
}

// SaveLastResult provides a mock function for the type MockRateLimiter
func (_mock *MockRateLimiter) SaveLastResult(ctx context.Context, ip string, uaHash string, route string, payload []byte) error {
	ret := _mock.Called(ctx, ip, uaHash, route, payload)

	if len(ret) == 0 {
		panic("no return value specified for SaveLastResult")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []byte) error); ok {
		r0 = returnFunc(ctx, ip, uaHash, route, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRateLimiter_SaveLastResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveLastResult'
type MockRateLimiter_SaveLastResult_Call struct {
	*mock.Call
}

// SaveLastResult is a helper method to define mock.On call
//   - ctx context.Context
//   - ip string
//   - uaHash string
//   - route string
//   - payload []byte
func (_e *MockRateLimiter_Expecter) SaveLastResult(ctx interface{}, ip interface{}, uaHash interface{}, route interface{}, payload interface{}) *MockRateLimiter_SaveLastResult_Call {
	return &MockRateLimiter_SaveLastResult_Call{Call: _e.mock.On("SaveLastResult", ctx, ip, uaHash, route, payload)}
}

func (_c *MockRateLimiter_SaveLastResult_Call) Run(run func(ctx context.Context, ip string, uaHash string, route string, payload []byte)) *MockRateLimiter_SaveLastResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []byte
		if args[4] != nil {
			arg4 = args[4].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRateLimiter_SaveLastResult_Call) Return(err error) *MockRateLimiter_SaveLastResult_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRateLimiter_SaveLastResult_Call) RunAndReturn(run func(ctx context.Context, ip string, uaHash string, route string, payload []byte) error) *MockRateLimiter_SaveLastResult_Call {
	_c.Call.Return(run)
	return _c
}
