// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"word_app/backend/ent/externalauth"
	"word_app/backend/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExternalAuthCreate is the builder for creating a ExternalAuth entity.
type ExternalAuthCreate struct {
	config
	mutation *ExternalAuthMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProvider sets the "provider" field.
func (eac *ExternalAuthCreate) SetProvider(s string) *ExternalAuthCreate {
	eac.mutation.SetProvider(s)
	return eac
}

// SetProviderUserID sets the "provider_user_id" field.
func (eac *ExternalAuthCreate) SetProviderUserID(s string) *ExternalAuthCreate {
	eac.mutation.SetProviderUserID(s)
	return eac
}

// SetUserID sets the "user" edge to the User entity by ID.
func (eac *ExternalAuthCreate) SetUserID(id int) *ExternalAuthCreate {
	eac.mutation.SetUserID(id)
	return eac
}

// SetUser sets the "user" edge to the User entity.
func (eac *ExternalAuthCreate) SetUser(u *User) *ExternalAuthCreate {
	return eac.SetUserID(u.ID)
}

// Mutation returns the ExternalAuthMutation object of the builder.
func (eac *ExternalAuthCreate) Mutation() *ExternalAuthMutation {
	return eac.mutation
}

// Save creates the ExternalAuth in the database.
func (eac *ExternalAuthCreate) Save(ctx context.Context) (*ExternalAuth, error) {
	return withHooks(ctx, eac.sqlSave, eac.mutation, eac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (eac *ExternalAuthCreate) SaveX(ctx context.Context) *ExternalAuth {
	v, err := eac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (eac *ExternalAuthCreate) Exec(ctx context.Context) error {
	_, err := eac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eac *ExternalAuthCreate) ExecX(ctx context.Context) {
	if err := eac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eac *ExternalAuthCreate) check() error {
	if _, ok := eac.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "ExternalAuth.provider"`)}
	}
	if v, ok := eac.mutation.Provider(); ok {
		if err := externalauth.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ExternalAuth.provider": %w`, err)}
		}
	}
	if _, ok := eac.mutation.ProviderUserID(); !ok {
		return &ValidationError{Name: "provider_user_id", err: errors.New(`ent: missing required field "ExternalAuth.provider_user_id"`)}
	}
	if v, ok := eac.mutation.ProviderUserID(); ok {
		if err := externalauth.ProviderUserIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_user_id", err: fmt.Errorf(`ent: validator failed for field "ExternalAuth.provider_user_id": %w`, err)}
		}
	}
	if len(eac.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ExternalAuth.user"`)}
	}
	return nil
}

func (eac *ExternalAuthCreate) sqlSave(ctx context.Context) (*ExternalAuth, error) {
	if err := eac.check(); err != nil {
		return nil, err
	}
	_node, _spec := eac.createSpec()
	if err := sqlgraph.CreateNode(ctx, eac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	eac.mutation.id = &_node.ID
	eac.mutation.done = true
	return _node, nil
}

func (eac *ExternalAuthCreate) createSpec() (*ExternalAuth, *sqlgraph.CreateSpec) {
	var (
		_node = &ExternalAuth{config: eac.config}
		_spec = sqlgraph.NewCreateSpec(externalauth.Table, sqlgraph.NewFieldSpec(externalauth.FieldID, field.TypeInt))
	)
	_spec.OnConflict = eac.conflict
	if value, ok := eac.mutation.Provider(); ok {
		_spec.SetField(externalauth.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := eac.mutation.ProviderUserID(); ok {
		_spec.SetField(externalauth.FieldProviderUserID, field.TypeString, value)
		_node.ProviderUserID = value
	}
	if nodes := eac.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   externalauth.UserTable,
			Columns: []string{externalauth.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_external_auths = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExternalAuth.Create().
//		SetProvider(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExternalAuthUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (eac *ExternalAuthCreate) OnConflict(opts ...sql.ConflictOption) *ExternalAuthUpsertOne {
	eac.conflict = opts
	return &ExternalAuthUpsertOne{
		create: eac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExternalAuth.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (eac *ExternalAuthCreate) OnConflictColumns(columns ...string) *ExternalAuthUpsertOne {
	eac.conflict = append(eac.conflict, sql.ConflictColumns(columns...))
	return &ExternalAuthUpsertOne{
		create: eac,
	}
}

type (
	// ExternalAuthUpsertOne is the builder for "upsert"-ing
	//  one ExternalAuth node.
	ExternalAuthUpsertOne struct {
		create *ExternalAuthCreate
	}

	// ExternalAuthUpsert is the "OnConflict" setter.
	ExternalAuthUpsert struct {
		*sql.UpdateSet
	}
)

// SetProvider sets the "provider" field.
func (u *ExternalAuthUpsert) SetProvider(v string) *ExternalAuthUpsert {
	u.Set(externalauth.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ExternalAuthUpsert) UpdateProvider() *ExternalAuthUpsert {
	u.SetExcluded(externalauth.FieldProvider)
	return u
}

// SetProviderUserID sets the "provider_user_id" field.
func (u *ExternalAuthUpsert) SetProviderUserID(v string) *ExternalAuthUpsert {
	u.Set(externalauth.FieldProviderUserID, v)
	return u
}

// UpdateProviderUserID sets the "provider_user_id" field to the value that was provided on create.
func (u *ExternalAuthUpsert) UpdateProviderUserID() *ExternalAuthUpsert {
	u.SetExcluded(externalauth.FieldProviderUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ExternalAuth.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ExternalAuthUpsertOne) UpdateNewValues() *ExternalAuthUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExternalAuth.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExternalAuthUpsertOne) Ignore() *ExternalAuthUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExternalAuthUpsertOne) DoNothing() *ExternalAuthUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExternalAuthCreate.OnConflict
// documentation for more info.
func (u *ExternalAuthUpsertOne) Update(set func(*ExternalAuthUpsert)) *ExternalAuthUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExternalAuthUpsert{UpdateSet: update})
	}))
	return u
}

// SetProvider sets the "provider" field.
func (u *ExternalAuthUpsertOne) SetProvider(v string) *ExternalAuthUpsertOne {
	return u.Update(func(s *ExternalAuthUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ExternalAuthUpsertOne) UpdateProvider() *ExternalAuthUpsertOne {
	return u.Update(func(s *ExternalAuthUpsert) {
		s.UpdateProvider()
	})
}

// SetProviderUserID sets the "provider_user_id" field.
func (u *ExternalAuthUpsertOne) SetProviderUserID(v string) *ExternalAuthUpsertOne {
	return u.Update(func(s *ExternalAuthUpsert) {
		s.SetProviderUserID(v)
	})
}

// UpdateProviderUserID sets the "provider_user_id" field to the value that was provided on create.
func (u *ExternalAuthUpsertOne) UpdateProviderUserID() *ExternalAuthUpsertOne {
	return u.Update(func(s *ExternalAuthUpsert) {
		s.UpdateProviderUserID()
	})
}

// Exec executes the query.
func (u *ExternalAuthUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExternalAuthCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExternalAuthUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExternalAuthUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExternalAuthUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExternalAuthCreateBulk is the builder for creating many ExternalAuth entities in bulk.
type ExternalAuthCreateBulk struct {
	config
	err      error
	builders []*ExternalAuthCreate
	conflict []sql.ConflictOption
}

// Save creates the ExternalAuth entities in the database.
func (eacb *ExternalAuthCreateBulk) Save(ctx context.Context) ([]*ExternalAuth, error) {
	if eacb.err != nil {
		return nil, eacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(eacb.builders))
	nodes := make([]*ExternalAuth, len(eacb.builders))
	mutators := make([]Mutator, len(eacb.builders))
	for i := range eacb.builders {
		func(i int, root context.Context) {
			builder := eacb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExternalAuthMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, eacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = eacb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, eacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, eacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (eacb *ExternalAuthCreateBulk) SaveX(ctx context.Context) []*ExternalAuth {
	v, err := eacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (eacb *ExternalAuthCreateBulk) Exec(ctx context.Context) error {
	_, err := eacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eacb *ExternalAuthCreateBulk) ExecX(ctx context.Context) {
	if err := eacb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExternalAuth.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExternalAuthUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (eacb *ExternalAuthCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExternalAuthUpsertBulk {
	eacb.conflict = opts
	return &ExternalAuthUpsertBulk{
		create: eacb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExternalAuth.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (eacb *ExternalAuthCreateBulk) OnConflictColumns(columns ...string) *ExternalAuthUpsertBulk {
	eacb.conflict = append(eacb.conflict, sql.ConflictColumns(columns...))
	return &ExternalAuthUpsertBulk{
		create: eacb,
	}
}

// ExternalAuthUpsertBulk is the builder for "upsert"-ing
// a bulk of ExternalAuth nodes.
type ExternalAuthUpsertBulk struct {
	create *ExternalAuthCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ExternalAuth.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ExternalAuthUpsertBulk) UpdateNewValues() *ExternalAuthUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExternalAuth.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExternalAuthUpsertBulk) Ignore() *ExternalAuthUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExternalAuthUpsertBulk) DoNothing() *ExternalAuthUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExternalAuthCreateBulk.OnConflict
// documentation for more info.
func (u *ExternalAuthUpsertBulk) Update(set func(*ExternalAuthUpsert)) *ExternalAuthUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExternalAuthUpsert{UpdateSet: update})
	}))
	return u
}

// SetProvider sets the "provider" field.
func (u *ExternalAuthUpsertBulk) SetProvider(v string) *ExternalAuthUpsertBulk {
	return u.Update(func(s *ExternalAuthUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ExternalAuthUpsertBulk) UpdateProvider() *ExternalAuthUpsertBulk {
	return u.Update(func(s *ExternalAuthUpsert) {
		s.UpdateProvider()
	})
}

// SetProviderUserID sets the "provider_user_id" field.
func (u *ExternalAuthUpsertBulk) SetProviderUserID(v string) *ExternalAuthUpsertBulk {
	return u.Update(func(s *ExternalAuthUpsert) {
		s.SetProviderUserID(v)
	})
}

// UpdateProviderUserID sets the "provider_user_id" field to the value that was provided on create.
func (u *ExternalAuthUpsertBulk) UpdateProviderUserID() *ExternalAuthUpsertBulk {
	return u.Update(func(s *ExternalAuthUpsert) {
		s.UpdateProviderUserID()
	})
}

// Exec executes the query.
func (u *ExternalAuthUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ExternalAuthCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExternalAuthCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExternalAuthUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
