// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"word_app/backend/ent/japanesemean"
	"word_app/backend/ent/wordinfo"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JapaneseMeanCreate is the builder for creating a JapaneseMean entity.
type JapaneseMeanCreate struct {
	config
	mutation *JapaneseMeanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (jmc *JapaneseMeanCreate) SetName(s string) *JapaneseMeanCreate {
	jmc.mutation.SetName(s)
	return jmc
}

// SetWordInfoID sets the "word_info_id" field.
func (jmc *JapaneseMeanCreate) SetWordInfoID(i int) *JapaneseMeanCreate {
	jmc.mutation.SetWordInfoID(i)
	return jmc
}

// SetCreatedAt sets the "created_at" field.
func (jmc *JapaneseMeanCreate) SetCreatedAt(t time.Time) *JapaneseMeanCreate {
	jmc.mutation.SetCreatedAt(t)
	return jmc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (jmc *JapaneseMeanCreate) SetNillableCreatedAt(t *time.Time) *JapaneseMeanCreate {
	if t != nil {
		jmc.SetCreatedAt(*t)
	}
	return jmc
}

// SetUpdatedAt sets the "updated_at" field.
func (jmc *JapaneseMeanCreate) SetUpdatedAt(t time.Time) *JapaneseMeanCreate {
	jmc.mutation.SetUpdatedAt(t)
	return jmc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (jmc *JapaneseMeanCreate) SetNillableUpdatedAt(t *time.Time) *JapaneseMeanCreate {
	if t != nil {
		jmc.SetUpdatedAt(*t)
	}
	return jmc
}

// SetWordInfo sets the "word_info" edge to the WordInfo entity.
func (jmc *JapaneseMeanCreate) SetWordInfo(w *WordInfo) *JapaneseMeanCreate {
	return jmc.SetWordInfoID(w.ID)
}

// Mutation returns the JapaneseMeanMutation object of the builder.
func (jmc *JapaneseMeanCreate) Mutation() *JapaneseMeanMutation {
	return jmc.mutation
}

// Save creates the JapaneseMean in the database.
func (jmc *JapaneseMeanCreate) Save(ctx context.Context) (*JapaneseMean, error) {
	jmc.defaults()
	return withHooks(ctx, jmc.sqlSave, jmc.mutation, jmc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (jmc *JapaneseMeanCreate) SaveX(ctx context.Context) *JapaneseMean {
	v, err := jmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jmc *JapaneseMeanCreate) Exec(ctx context.Context) error {
	_, err := jmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jmc *JapaneseMeanCreate) ExecX(ctx context.Context) {
	if err := jmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (jmc *JapaneseMeanCreate) defaults() {
	if _, ok := jmc.mutation.CreatedAt(); !ok {
		v := japanesemean.DefaultCreatedAt()
		jmc.mutation.SetCreatedAt(v)
	}
	if _, ok := jmc.mutation.UpdatedAt(); !ok {
		v := japanesemean.DefaultUpdatedAt()
		jmc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (jmc *JapaneseMeanCreate) check() error {
	if _, ok := jmc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "JapaneseMean.name"`)}
	}
	if v, ok := jmc.mutation.Name(); ok {
		if err := japanesemean.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "JapaneseMean.name": %w`, err)}
		}
	}
	if _, ok := jmc.mutation.WordInfoID(); !ok {
		return &ValidationError{Name: "word_info_id", err: errors.New(`ent: missing required field "JapaneseMean.word_info_id"`)}
	}
	if v, ok := jmc.mutation.WordInfoID(); ok {
		if err := japanesemean.WordInfoIDValidator(v); err != nil {
			return &ValidationError{Name: "word_info_id", err: fmt.Errorf(`ent: validator failed for field "JapaneseMean.word_info_id": %w`, err)}
		}
	}
	if _, ok := jmc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "JapaneseMean.created_at"`)}
	}
	if _, ok := jmc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "JapaneseMean.updated_at"`)}
	}
	if len(jmc.mutation.WordInfoIDs()) == 0 {
		return &ValidationError{Name: "word_info", err: errors.New(`ent: missing required edge "JapaneseMean.word_info"`)}
	}
	return nil
}

func (jmc *JapaneseMeanCreate) sqlSave(ctx context.Context) (*JapaneseMean, error) {
	if err := jmc.check(); err != nil {
		return nil, err
	}
	_node, _spec := jmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, jmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	jmc.mutation.id = &_node.ID
	jmc.mutation.done = true
	return _node, nil
}

func (jmc *JapaneseMeanCreate) createSpec() (*JapaneseMean, *sqlgraph.CreateSpec) {
	var (
		_node = &JapaneseMean{config: jmc.config}
		_spec = sqlgraph.NewCreateSpec(japanesemean.Table, sqlgraph.NewFieldSpec(japanesemean.FieldID, field.TypeInt))
	)
	_spec.OnConflict = jmc.conflict
	if value, ok := jmc.mutation.Name(); ok {
		_spec.SetField(japanesemean.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := jmc.mutation.CreatedAt(); ok {
		_spec.SetField(japanesemean.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := jmc.mutation.UpdatedAt(); ok {
		_spec.SetField(japanesemean.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := jmc.mutation.WordInfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   japanesemean.WordInfoTable,
			Columns: []string{japanesemean.WordInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordinfo.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WordInfoID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.JapaneseMean.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.JapaneseMeanUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (jmc *JapaneseMeanCreate) OnConflict(opts ...sql.ConflictOption) *JapaneseMeanUpsertOne {
	jmc.conflict = opts
	return &JapaneseMeanUpsertOne{
		create: jmc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.JapaneseMean.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (jmc *JapaneseMeanCreate) OnConflictColumns(columns ...string) *JapaneseMeanUpsertOne {
	jmc.conflict = append(jmc.conflict, sql.ConflictColumns(columns...))
	return &JapaneseMeanUpsertOne{
		create: jmc,
	}
}

type (
	// JapaneseMeanUpsertOne is the builder for "upsert"-ing
	//  one JapaneseMean node.
	JapaneseMeanUpsertOne struct {
		create *JapaneseMeanCreate
	}

	// JapaneseMeanUpsert is the "OnConflict" setter.
	JapaneseMeanUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *JapaneseMeanUpsert) SetName(v string) *JapaneseMeanUpsert {
	u.Set(japanesemean.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *JapaneseMeanUpsert) UpdateName() *JapaneseMeanUpsert {
	u.SetExcluded(japanesemean.FieldName)
	return u
}

// SetWordInfoID sets the "word_info_id" field.
func (u *JapaneseMeanUpsert) SetWordInfoID(v int) *JapaneseMeanUpsert {
	u.Set(japanesemean.FieldWordInfoID, v)
	return u
}

// UpdateWordInfoID sets the "word_info_id" field to the value that was provided on create.
func (u *JapaneseMeanUpsert) UpdateWordInfoID() *JapaneseMeanUpsert {
	u.SetExcluded(japanesemean.FieldWordInfoID)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *JapaneseMeanUpsert) SetCreatedAt(v time.Time) *JapaneseMeanUpsert {
	u.Set(japanesemean.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *JapaneseMeanUpsert) UpdateCreatedAt() *JapaneseMeanUpsert {
	u.SetExcluded(japanesemean.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *JapaneseMeanUpsert) SetUpdatedAt(v time.Time) *JapaneseMeanUpsert {
	u.Set(japanesemean.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *JapaneseMeanUpsert) UpdateUpdatedAt() *JapaneseMeanUpsert {
	u.SetExcluded(japanesemean.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.JapaneseMean.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *JapaneseMeanUpsertOne) UpdateNewValues() *JapaneseMeanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.JapaneseMean.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *JapaneseMeanUpsertOne) Ignore() *JapaneseMeanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *JapaneseMeanUpsertOne) DoNothing() *JapaneseMeanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the JapaneseMeanCreate.OnConflict
// documentation for more info.
func (u *JapaneseMeanUpsertOne) Update(set func(*JapaneseMeanUpsert)) *JapaneseMeanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&JapaneseMeanUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *JapaneseMeanUpsertOne) SetName(v string) *JapaneseMeanUpsertOne {
	return u.Update(func(s *JapaneseMeanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *JapaneseMeanUpsertOne) UpdateName() *JapaneseMeanUpsertOne {
	return u.Update(func(s *JapaneseMeanUpsert) {
		s.UpdateName()
	})
}

// SetWordInfoID sets the "word_info_id" field.
func (u *JapaneseMeanUpsertOne) SetWordInfoID(v int) *JapaneseMeanUpsertOne {
	return u.Update(func(s *JapaneseMeanUpsert) {
		s.SetWordInfoID(v)
	})
}

// UpdateWordInfoID sets the "word_info_id" field to the value that was provided on create.
func (u *JapaneseMeanUpsertOne) UpdateWordInfoID() *JapaneseMeanUpsertOne {
	return u.Update(func(s *JapaneseMeanUpsert) {
		s.UpdateWordInfoID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *JapaneseMeanUpsertOne) SetCreatedAt(v time.Time) *JapaneseMeanUpsertOne {
	return u.Update(func(s *JapaneseMeanUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *JapaneseMeanUpsertOne) UpdateCreatedAt() *JapaneseMeanUpsertOne {
	return u.Update(func(s *JapaneseMeanUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *JapaneseMeanUpsertOne) SetUpdatedAt(v time.Time) *JapaneseMeanUpsertOne {
	return u.Update(func(s *JapaneseMeanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *JapaneseMeanUpsertOne) UpdateUpdatedAt() *JapaneseMeanUpsertOne {
	return u.Update(func(s *JapaneseMeanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *JapaneseMeanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for JapaneseMeanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *JapaneseMeanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *JapaneseMeanUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *JapaneseMeanUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// JapaneseMeanCreateBulk is the builder for creating many JapaneseMean entities in bulk.
type JapaneseMeanCreateBulk struct {
	config
	err      error
	builders []*JapaneseMeanCreate
	conflict []sql.ConflictOption
}

// Save creates the JapaneseMean entities in the database.
func (jmcb *JapaneseMeanCreateBulk) Save(ctx context.Context) ([]*JapaneseMean, error) {
	if jmcb.err != nil {
		return nil, jmcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(jmcb.builders))
	nodes := make([]*JapaneseMean, len(jmcb.builders))
	mutators := make([]Mutator, len(jmcb.builders))
	for i := range jmcb.builders {
		func(i int, root context.Context) {
			builder := jmcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JapaneseMeanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, jmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = jmcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, jmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, jmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (jmcb *JapaneseMeanCreateBulk) SaveX(ctx context.Context) []*JapaneseMean {
	v, err := jmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jmcb *JapaneseMeanCreateBulk) Exec(ctx context.Context) error {
	_, err := jmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jmcb *JapaneseMeanCreateBulk) ExecX(ctx context.Context) {
	if err := jmcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.JapaneseMean.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.JapaneseMeanUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (jmcb *JapaneseMeanCreateBulk) OnConflict(opts ...sql.ConflictOption) *JapaneseMeanUpsertBulk {
	jmcb.conflict = opts
	return &JapaneseMeanUpsertBulk{
		create: jmcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.JapaneseMean.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (jmcb *JapaneseMeanCreateBulk) OnConflictColumns(columns ...string) *JapaneseMeanUpsertBulk {
	jmcb.conflict = append(jmcb.conflict, sql.ConflictColumns(columns...))
	return &JapaneseMeanUpsertBulk{
		create: jmcb,
	}
}

// JapaneseMeanUpsertBulk is the builder for "upsert"-ing
// a bulk of JapaneseMean nodes.
type JapaneseMeanUpsertBulk struct {
	create *JapaneseMeanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.JapaneseMean.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *JapaneseMeanUpsertBulk) UpdateNewValues() *JapaneseMeanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.JapaneseMean.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *JapaneseMeanUpsertBulk) Ignore() *JapaneseMeanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *JapaneseMeanUpsertBulk) DoNothing() *JapaneseMeanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the JapaneseMeanCreateBulk.OnConflict
// documentation for more info.
func (u *JapaneseMeanUpsertBulk) Update(set func(*JapaneseMeanUpsert)) *JapaneseMeanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&JapaneseMeanUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *JapaneseMeanUpsertBulk) SetName(v string) *JapaneseMeanUpsertBulk {
	return u.Update(func(s *JapaneseMeanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *JapaneseMeanUpsertBulk) UpdateName() *JapaneseMeanUpsertBulk {
	return u.Update(func(s *JapaneseMeanUpsert) {
		s.UpdateName()
	})
}

// SetWordInfoID sets the "word_info_id" field.
func (u *JapaneseMeanUpsertBulk) SetWordInfoID(v int) *JapaneseMeanUpsertBulk {
	return u.Update(func(s *JapaneseMeanUpsert) {
		s.SetWordInfoID(v)
	})
}

// UpdateWordInfoID sets the "word_info_id" field to the value that was provided on create.
func (u *JapaneseMeanUpsertBulk) UpdateWordInfoID() *JapaneseMeanUpsertBulk {
	return u.Update(func(s *JapaneseMeanUpsert) {
		s.UpdateWordInfoID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *JapaneseMeanUpsertBulk) SetCreatedAt(v time.Time) *JapaneseMeanUpsertBulk {
	return u.Update(func(s *JapaneseMeanUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *JapaneseMeanUpsertBulk) UpdateCreatedAt() *JapaneseMeanUpsertBulk {
	return u.Update(func(s *JapaneseMeanUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *JapaneseMeanUpsertBulk) SetUpdatedAt(v time.Time) *JapaneseMeanUpsertBulk {
	return u.Update(func(s *JapaneseMeanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *JapaneseMeanUpsertBulk) UpdateUpdatedAt() *JapaneseMeanUpsertBulk {
	return u.Update(func(s *JapaneseMeanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *JapaneseMeanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the JapaneseMeanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for JapaneseMeanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *JapaneseMeanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
