// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"word_app/backend/ent/partofspeech"
	"word_app/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PartOfSpeechDelete is the builder for deleting a PartOfSpeech entity.
type PartOfSpeechDelete struct {
	config
	hooks    []Hook
	mutation *PartOfSpeechMutation
}

// Where appends a list predicates to the PartOfSpeechDelete builder.
func (posd *PartOfSpeechDelete) Where(ps ...predicate.PartOfSpeech) *PartOfSpeechDelete {
	posd.mutation.Where(ps...)
	return posd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (posd *PartOfSpeechDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, posd.sqlExec, posd.mutation, posd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (posd *PartOfSpeechDelete) ExecX(ctx context.Context) int {
	n, err := posd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (posd *PartOfSpeechDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(partofspeech.Table, sqlgraph.NewFieldSpec(partofspeech.FieldID, field.TypeInt))
	if ps := posd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, posd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	posd.mutation.done = true
	return affected, err
}

// PartOfSpeechDeleteOne is the builder for deleting a single PartOfSpeech entity.
type PartOfSpeechDeleteOne struct {
	posd *PartOfSpeechDelete
}

// Where appends a list predicates to the PartOfSpeechDelete builder.
func (posdo *PartOfSpeechDeleteOne) Where(ps ...predicate.PartOfSpeech) *PartOfSpeechDeleteOne {
	posdo.posd.mutation.Where(ps...)
	return posdo
}

// Exec executes the deletion query.
func (posdo *PartOfSpeechDeleteOne) Exec(ctx context.Context) error {
	n, err := posdo.posd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{partofspeech.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (posdo *PartOfSpeechDeleteOne) ExecX(ctx context.Context) {
	if err := posdo.Exec(ctx); err != nil {
		panic(err)
	}
}
