// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"word_app/backend/ent/japanesemean"
	"word_app/backend/ent/quiz"
	"word_app/backend/ent/quizquestion"
	"word_app/backend/ent/word"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuizQuestionCreate is the builder for creating a QuizQuestion entity.
type QuizQuestionCreate struct {
	config
	mutation *QuizQuestionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetQuizID sets the "quiz_id" field.
func (qqc *QuizQuestionCreate) SetQuizID(i int) *QuizQuestionCreate {
	qqc.mutation.SetQuizID(i)
	return qqc
}

// SetQuestionNumber sets the "question_number" field.
func (qqc *QuizQuestionCreate) SetQuestionNumber(i int) *QuizQuestionCreate {
	qqc.mutation.SetQuestionNumber(i)
	return qqc
}

// SetWordID sets the "word_id" field.
func (qqc *QuizQuestionCreate) SetWordID(i int) *QuizQuestionCreate {
	qqc.mutation.SetWordID(i)
	return qqc
}

// SetCorrectJpmID sets the "correct_jpm_id" field.
func (qqc *QuizQuestionCreate) SetCorrectJpmID(i int) *QuizQuestionCreate {
	qqc.mutation.SetCorrectJpmID(i)
	return qqc
}

// SetChoicesJpmIds sets the "choices_jpm_ids" field.
func (qqc *QuizQuestionCreate) SetChoicesJpmIds(i []int) *QuizQuestionCreate {
	qqc.mutation.SetChoicesJpmIds(i)
	return qqc
}

// SetAnswerJpmID sets the "answer_jpm_id" field.
func (qqc *QuizQuestionCreate) SetAnswerJpmID(i int) *QuizQuestionCreate {
	qqc.mutation.SetAnswerJpmID(i)
	return qqc
}

// SetIsCorrect sets the "is_correct" field.
func (qqc *QuizQuestionCreate) SetIsCorrect(b bool) *QuizQuestionCreate {
	qqc.mutation.SetIsCorrect(b)
	return qqc
}

// SetAnsweredAt sets the "answered_at" field.
func (qqc *QuizQuestionCreate) SetAnsweredAt(t time.Time) *QuizQuestionCreate {
	qqc.mutation.SetAnsweredAt(t)
	return qqc
}

// SetTimeMs sets the "time_ms" field.
func (qqc *QuizQuestionCreate) SetTimeMs(i int) *QuizQuestionCreate {
	qqc.mutation.SetTimeMs(i)
	return qqc
}

// SetCreatedAt sets the "created_at" field.
func (qqc *QuizQuestionCreate) SetCreatedAt(t time.Time) *QuizQuestionCreate {
	qqc.mutation.SetCreatedAt(t)
	return qqc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (qqc *QuizQuestionCreate) SetNillableCreatedAt(t *time.Time) *QuizQuestionCreate {
	if t != nil {
		qqc.SetCreatedAt(*t)
	}
	return qqc
}

// SetDeletedAt sets the "deleted_at" field.
func (qqc *QuizQuestionCreate) SetDeletedAt(t time.Time) *QuizQuestionCreate {
	qqc.mutation.SetDeletedAt(t)
	return qqc
}

// SetQuiz sets the "quiz" edge to the Quiz entity.
func (qqc *QuizQuestionCreate) SetQuiz(q *Quiz) *QuizQuestionCreate {
	return qqc.SetQuizID(q.ID)
}

// SetWord sets the "word" edge to the Word entity.
func (qqc *QuizQuestionCreate) SetWord(w *Word) *QuizQuestionCreate {
	return qqc.SetWordID(w.ID)
}

// SetJapaneseMeanID sets the "japanese_mean" edge to the JapaneseMean entity by ID.
func (qqc *QuizQuestionCreate) SetJapaneseMeanID(id int) *QuizQuestionCreate {
	qqc.mutation.SetJapaneseMeanID(id)
	return qqc
}

// SetJapaneseMean sets the "japanese_mean" edge to the JapaneseMean entity.
func (qqc *QuizQuestionCreate) SetJapaneseMean(j *JapaneseMean) *QuizQuestionCreate {
	return qqc.SetJapaneseMeanID(j.ID)
}

// Mutation returns the QuizQuestionMutation object of the builder.
func (qqc *QuizQuestionCreate) Mutation() *QuizQuestionMutation {
	return qqc.mutation
}

// Save creates the QuizQuestion in the database.
func (qqc *QuizQuestionCreate) Save(ctx context.Context) (*QuizQuestion, error) {
	qqc.defaults()
	return withHooks(ctx, qqc.sqlSave, qqc.mutation, qqc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (qqc *QuizQuestionCreate) SaveX(ctx context.Context) *QuizQuestion {
	v, err := qqc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qqc *QuizQuestionCreate) Exec(ctx context.Context) error {
	_, err := qqc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qqc *QuizQuestionCreate) ExecX(ctx context.Context) {
	if err := qqc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (qqc *QuizQuestionCreate) defaults() {
	if _, ok := qqc.mutation.CreatedAt(); !ok {
		v := quizquestion.DefaultCreatedAt()
		qqc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (qqc *QuizQuestionCreate) check() error {
	if _, ok := qqc.mutation.QuizID(); !ok {
		return &ValidationError{Name: "quiz_id", err: errors.New(`ent: missing required field "QuizQuestion.quiz_id"`)}
	}
	if _, ok := qqc.mutation.QuestionNumber(); !ok {
		return &ValidationError{Name: "question_number", err: errors.New(`ent: missing required field "QuizQuestion.question_number"`)}
	}
	if _, ok := qqc.mutation.WordID(); !ok {
		return &ValidationError{Name: "word_id", err: errors.New(`ent: missing required field "QuizQuestion.word_id"`)}
	}
	if v, ok := qqc.mutation.WordID(); ok {
		if err := quizquestion.WordIDValidator(v); err != nil {
			return &ValidationError{Name: "word_id", err: fmt.Errorf(`ent: validator failed for field "QuizQuestion.word_id": %w`, err)}
		}
	}
	if _, ok := qqc.mutation.CorrectJpmID(); !ok {
		return &ValidationError{Name: "correct_jpm_id", err: errors.New(`ent: missing required field "QuizQuestion.correct_jpm_id"`)}
	}
	if _, ok := qqc.mutation.ChoicesJpmIds(); !ok {
		return &ValidationError{Name: "choices_jpm_ids", err: errors.New(`ent: missing required field "QuizQuestion.choices_jpm_ids"`)}
	}
	if _, ok := qqc.mutation.AnswerJpmID(); !ok {
		return &ValidationError{Name: "answer_jpm_id", err: errors.New(`ent: missing required field "QuizQuestion.answer_jpm_id"`)}
	}
	if _, ok := qqc.mutation.IsCorrect(); !ok {
		return &ValidationError{Name: "is_correct", err: errors.New(`ent: missing required field "QuizQuestion.is_correct"`)}
	}
	if _, ok := qqc.mutation.AnsweredAt(); !ok {
		return &ValidationError{Name: "answered_at", err: errors.New(`ent: missing required field "QuizQuestion.answered_at"`)}
	}
	if _, ok := qqc.mutation.TimeMs(); !ok {
		return &ValidationError{Name: "time_ms", err: errors.New(`ent: missing required field "QuizQuestion.time_ms"`)}
	}
	if _, ok := qqc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "QuizQuestion.created_at"`)}
	}
	if _, ok := qqc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "QuizQuestion.deleted_at"`)}
	}
	if len(qqc.mutation.QuizIDs()) == 0 {
		return &ValidationError{Name: "quiz", err: errors.New(`ent: missing required edge "QuizQuestion.quiz"`)}
	}
	if len(qqc.mutation.WordIDs()) == 0 {
		return &ValidationError{Name: "word", err: errors.New(`ent: missing required edge "QuizQuestion.word"`)}
	}
	if len(qqc.mutation.JapaneseMeanIDs()) == 0 {
		return &ValidationError{Name: "japanese_mean", err: errors.New(`ent: missing required edge "QuizQuestion.japanese_mean"`)}
	}
	return nil
}

func (qqc *QuizQuestionCreate) sqlSave(ctx context.Context) (*QuizQuestion, error) {
	if err := qqc.check(); err != nil {
		return nil, err
	}
	_node, _spec := qqc.createSpec()
	if err := sqlgraph.CreateNode(ctx, qqc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	qqc.mutation.id = &_node.ID
	qqc.mutation.done = true
	return _node, nil
}

func (qqc *QuizQuestionCreate) createSpec() (*QuizQuestion, *sqlgraph.CreateSpec) {
	var (
		_node = &QuizQuestion{config: qqc.config}
		_spec = sqlgraph.NewCreateSpec(quizquestion.Table, sqlgraph.NewFieldSpec(quizquestion.FieldID, field.TypeInt))
	)
	_spec.OnConflict = qqc.conflict
	if value, ok := qqc.mutation.QuestionNumber(); ok {
		_spec.SetField(quizquestion.FieldQuestionNumber, field.TypeInt, value)
		_node.QuestionNumber = value
	}
	if value, ok := qqc.mutation.ChoicesJpmIds(); ok {
		_spec.SetField(quizquestion.FieldChoicesJpmIds, field.TypeJSON, value)
		_node.ChoicesJpmIds = value
	}
	if value, ok := qqc.mutation.AnswerJpmID(); ok {
		_spec.SetField(quizquestion.FieldAnswerJpmID, field.TypeInt, value)
		_node.AnswerJpmID = &value
	}
	if value, ok := qqc.mutation.IsCorrect(); ok {
		_spec.SetField(quizquestion.FieldIsCorrect, field.TypeBool, value)
		_node.IsCorrect = &value
	}
	if value, ok := qqc.mutation.AnsweredAt(); ok {
		_spec.SetField(quizquestion.FieldAnsweredAt, field.TypeTime, value)
		_node.AnsweredAt = &value
	}
	if value, ok := qqc.mutation.TimeMs(); ok {
		_spec.SetField(quizquestion.FieldTimeMs, field.TypeInt, value)
		_node.TimeMs = &value
	}
	if value, ok := qqc.mutation.CreatedAt(); ok {
		_spec.SetField(quizquestion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := qqc.mutation.DeletedAt(); ok {
		_spec.SetField(quizquestion.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if nodes := qqc.mutation.QuizIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizquestion.QuizTable,
			Columns: []string{quizquestion.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.QuizID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := qqc.mutation.WordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizquestion.WordTable,
			Columns: []string{quizquestion.WordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(word.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WordID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := qqc.mutation.JapaneseMeanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizquestion.JapaneseMeanTable,
			Columns: []string{quizquestion.JapaneseMeanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(japanesemean.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CorrectJpmID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.QuizQuestion.Create().
//		SetQuizID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuizQuestionUpsert) {
//			SetQuizID(v+v).
//		}).
//		Exec(ctx)
func (qqc *QuizQuestionCreate) OnConflict(opts ...sql.ConflictOption) *QuizQuestionUpsertOne {
	qqc.conflict = opts
	return &QuizQuestionUpsertOne{
		create: qqc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.QuizQuestion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (qqc *QuizQuestionCreate) OnConflictColumns(columns ...string) *QuizQuestionUpsertOne {
	qqc.conflict = append(qqc.conflict, sql.ConflictColumns(columns...))
	return &QuizQuestionUpsertOne{
		create: qqc,
	}
}

type (
	// QuizQuestionUpsertOne is the builder for "upsert"-ing
	//  one QuizQuestion node.
	QuizQuestionUpsertOne struct {
		create *QuizQuestionCreate
	}

	// QuizQuestionUpsert is the "OnConflict" setter.
	QuizQuestionUpsert struct {
		*sql.UpdateSet
	}
)

// SetQuizID sets the "quiz_id" field.
func (u *QuizQuestionUpsert) SetQuizID(v int) *QuizQuestionUpsert {
	u.Set(quizquestion.FieldQuizID, v)
	return u
}

// UpdateQuizID sets the "quiz_id" field to the value that was provided on create.
func (u *QuizQuestionUpsert) UpdateQuizID() *QuizQuestionUpsert {
	u.SetExcluded(quizquestion.FieldQuizID)
	return u
}

// SetQuestionNumber sets the "question_number" field.
func (u *QuizQuestionUpsert) SetQuestionNumber(v int) *QuizQuestionUpsert {
	u.Set(quizquestion.FieldQuestionNumber, v)
	return u
}

// UpdateQuestionNumber sets the "question_number" field to the value that was provided on create.
func (u *QuizQuestionUpsert) UpdateQuestionNumber() *QuizQuestionUpsert {
	u.SetExcluded(quizquestion.FieldQuestionNumber)
	return u
}

// AddQuestionNumber adds v to the "question_number" field.
func (u *QuizQuestionUpsert) AddQuestionNumber(v int) *QuizQuestionUpsert {
	u.Add(quizquestion.FieldQuestionNumber, v)
	return u
}

// SetWordID sets the "word_id" field.
func (u *QuizQuestionUpsert) SetWordID(v int) *QuizQuestionUpsert {
	u.Set(quizquestion.FieldWordID, v)
	return u
}

// UpdateWordID sets the "word_id" field to the value that was provided on create.
func (u *QuizQuestionUpsert) UpdateWordID() *QuizQuestionUpsert {
	u.SetExcluded(quizquestion.FieldWordID)
	return u
}

// SetCorrectJpmID sets the "correct_jpm_id" field.
func (u *QuizQuestionUpsert) SetCorrectJpmID(v int) *QuizQuestionUpsert {
	u.Set(quizquestion.FieldCorrectJpmID, v)
	return u
}

// UpdateCorrectJpmID sets the "correct_jpm_id" field to the value that was provided on create.
func (u *QuizQuestionUpsert) UpdateCorrectJpmID() *QuizQuestionUpsert {
	u.SetExcluded(quizquestion.FieldCorrectJpmID)
	return u
}

// SetChoicesJpmIds sets the "choices_jpm_ids" field.
func (u *QuizQuestionUpsert) SetChoicesJpmIds(v []int) *QuizQuestionUpsert {
	u.Set(quizquestion.FieldChoicesJpmIds, v)
	return u
}

// UpdateChoicesJpmIds sets the "choices_jpm_ids" field to the value that was provided on create.
func (u *QuizQuestionUpsert) UpdateChoicesJpmIds() *QuizQuestionUpsert {
	u.SetExcluded(quizquestion.FieldChoicesJpmIds)
	return u
}

// SetAnswerJpmID sets the "answer_jpm_id" field.
func (u *QuizQuestionUpsert) SetAnswerJpmID(v int) *QuizQuestionUpsert {
	u.Set(quizquestion.FieldAnswerJpmID, v)
	return u
}

// UpdateAnswerJpmID sets the "answer_jpm_id" field to the value that was provided on create.
func (u *QuizQuestionUpsert) UpdateAnswerJpmID() *QuizQuestionUpsert {
	u.SetExcluded(quizquestion.FieldAnswerJpmID)
	return u
}

// AddAnswerJpmID adds v to the "answer_jpm_id" field.
func (u *QuizQuestionUpsert) AddAnswerJpmID(v int) *QuizQuestionUpsert {
	u.Add(quizquestion.FieldAnswerJpmID, v)
	return u
}

// SetIsCorrect sets the "is_correct" field.
func (u *QuizQuestionUpsert) SetIsCorrect(v bool) *QuizQuestionUpsert {
	u.Set(quizquestion.FieldIsCorrect, v)
	return u
}

// UpdateIsCorrect sets the "is_correct" field to the value that was provided on create.
func (u *QuizQuestionUpsert) UpdateIsCorrect() *QuizQuestionUpsert {
	u.SetExcluded(quizquestion.FieldIsCorrect)
	return u
}

// SetAnsweredAt sets the "answered_at" field.
func (u *QuizQuestionUpsert) SetAnsweredAt(v time.Time) *QuizQuestionUpsert {
	u.Set(quizquestion.FieldAnsweredAt, v)
	return u
}

// UpdateAnsweredAt sets the "answered_at" field to the value that was provided on create.
func (u *QuizQuestionUpsert) UpdateAnsweredAt() *QuizQuestionUpsert {
	u.SetExcluded(quizquestion.FieldAnsweredAt)
	return u
}

// SetTimeMs sets the "time_ms" field.
func (u *QuizQuestionUpsert) SetTimeMs(v int) *QuizQuestionUpsert {
	u.Set(quizquestion.FieldTimeMs, v)
	return u
}

// UpdateTimeMs sets the "time_ms" field to the value that was provided on create.
func (u *QuizQuestionUpsert) UpdateTimeMs() *QuizQuestionUpsert {
	u.SetExcluded(quizquestion.FieldTimeMs)
	return u
}

// AddTimeMs adds v to the "time_ms" field.
func (u *QuizQuestionUpsert) AddTimeMs(v int) *QuizQuestionUpsert {
	u.Add(quizquestion.FieldTimeMs, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *QuizQuestionUpsert) SetCreatedAt(v time.Time) *QuizQuestionUpsert {
	u.Set(quizquestion.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *QuizQuestionUpsert) UpdateCreatedAt() *QuizQuestionUpsert {
	u.SetExcluded(quizquestion.FieldCreatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *QuizQuestionUpsert) SetDeletedAt(v time.Time) *QuizQuestionUpsert {
	u.Set(quizquestion.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *QuizQuestionUpsert) UpdateDeletedAt() *QuizQuestionUpsert {
	u.SetExcluded(quizquestion.FieldDeletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.QuizQuestion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *QuizQuestionUpsertOne) UpdateNewValues() *QuizQuestionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.QuizQuestion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *QuizQuestionUpsertOne) Ignore() *QuizQuestionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuizQuestionUpsertOne) DoNothing() *QuizQuestionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuizQuestionCreate.OnConflict
// documentation for more info.
func (u *QuizQuestionUpsertOne) Update(set func(*QuizQuestionUpsert)) *QuizQuestionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuizQuestionUpsert{UpdateSet: update})
	}))
	return u
}

// SetQuizID sets the "quiz_id" field.
func (u *QuizQuestionUpsertOne) SetQuizID(v int) *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetQuizID(v)
	})
}

// UpdateQuizID sets the "quiz_id" field to the value that was provided on create.
func (u *QuizQuestionUpsertOne) UpdateQuizID() *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateQuizID()
	})
}

// SetQuestionNumber sets the "question_number" field.
func (u *QuizQuestionUpsertOne) SetQuestionNumber(v int) *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetQuestionNumber(v)
	})
}

// AddQuestionNumber adds v to the "question_number" field.
func (u *QuizQuestionUpsertOne) AddQuestionNumber(v int) *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.AddQuestionNumber(v)
	})
}

// UpdateQuestionNumber sets the "question_number" field to the value that was provided on create.
func (u *QuizQuestionUpsertOne) UpdateQuestionNumber() *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateQuestionNumber()
	})
}

// SetWordID sets the "word_id" field.
func (u *QuizQuestionUpsertOne) SetWordID(v int) *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetWordID(v)
	})
}

// UpdateWordID sets the "word_id" field to the value that was provided on create.
func (u *QuizQuestionUpsertOne) UpdateWordID() *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateWordID()
	})
}

// SetCorrectJpmID sets the "correct_jpm_id" field.
func (u *QuizQuestionUpsertOne) SetCorrectJpmID(v int) *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetCorrectJpmID(v)
	})
}

// UpdateCorrectJpmID sets the "correct_jpm_id" field to the value that was provided on create.
func (u *QuizQuestionUpsertOne) UpdateCorrectJpmID() *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateCorrectJpmID()
	})
}

// SetChoicesJpmIds sets the "choices_jpm_ids" field.
func (u *QuizQuestionUpsertOne) SetChoicesJpmIds(v []int) *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetChoicesJpmIds(v)
	})
}

// UpdateChoicesJpmIds sets the "choices_jpm_ids" field to the value that was provided on create.
func (u *QuizQuestionUpsertOne) UpdateChoicesJpmIds() *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateChoicesJpmIds()
	})
}

// SetAnswerJpmID sets the "answer_jpm_id" field.
func (u *QuizQuestionUpsertOne) SetAnswerJpmID(v int) *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetAnswerJpmID(v)
	})
}

// AddAnswerJpmID adds v to the "answer_jpm_id" field.
func (u *QuizQuestionUpsertOne) AddAnswerJpmID(v int) *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.AddAnswerJpmID(v)
	})
}

// UpdateAnswerJpmID sets the "answer_jpm_id" field to the value that was provided on create.
func (u *QuizQuestionUpsertOne) UpdateAnswerJpmID() *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateAnswerJpmID()
	})
}

// SetIsCorrect sets the "is_correct" field.
func (u *QuizQuestionUpsertOne) SetIsCorrect(v bool) *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetIsCorrect(v)
	})
}

// UpdateIsCorrect sets the "is_correct" field to the value that was provided on create.
func (u *QuizQuestionUpsertOne) UpdateIsCorrect() *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateIsCorrect()
	})
}

// SetAnsweredAt sets the "answered_at" field.
func (u *QuizQuestionUpsertOne) SetAnsweredAt(v time.Time) *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetAnsweredAt(v)
	})
}

// UpdateAnsweredAt sets the "answered_at" field to the value that was provided on create.
func (u *QuizQuestionUpsertOne) UpdateAnsweredAt() *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateAnsweredAt()
	})
}

// SetTimeMs sets the "time_ms" field.
func (u *QuizQuestionUpsertOne) SetTimeMs(v int) *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetTimeMs(v)
	})
}

// AddTimeMs adds v to the "time_ms" field.
func (u *QuizQuestionUpsertOne) AddTimeMs(v int) *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.AddTimeMs(v)
	})
}

// UpdateTimeMs sets the "time_ms" field to the value that was provided on create.
func (u *QuizQuestionUpsertOne) UpdateTimeMs() *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateTimeMs()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *QuizQuestionUpsertOne) SetCreatedAt(v time.Time) *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *QuizQuestionUpsertOne) UpdateCreatedAt() *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *QuizQuestionUpsertOne) SetDeletedAt(v time.Time) *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *QuizQuestionUpsertOne) UpdateDeletedAt() *QuizQuestionUpsertOne {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateDeletedAt()
	})
}

// Exec executes the query.
func (u *QuizQuestionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuizQuestionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuizQuestionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *QuizQuestionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *QuizQuestionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// QuizQuestionCreateBulk is the builder for creating many QuizQuestion entities in bulk.
type QuizQuestionCreateBulk struct {
	config
	err      error
	builders []*QuizQuestionCreate
	conflict []sql.ConflictOption
}

// Save creates the QuizQuestion entities in the database.
func (qqcb *QuizQuestionCreateBulk) Save(ctx context.Context) ([]*QuizQuestion, error) {
	if qqcb.err != nil {
		return nil, qqcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(qqcb.builders))
	nodes := make([]*QuizQuestion, len(qqcb.builders))
	mutators := make([]Mutator, len(qqcb.builders))
	for i := range qqcb.builders {
		func(i int, root context.Context) {
			builder := qqcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuizQuestionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, qqcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = qqcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, qqcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, qqcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (qqcb *QuizQuestionCreateBulk) SaveX(ctx context.Context) []*QuizQuestion {
	v, err := qqcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qqcb *QuizQuestionCreateBulk) Exec(ctx context.Context) error {
	_, err := qqcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qqcb *QuizQuestionCreateBulk) ExecX(ctx context.Context) {
	if err := qqcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.QuizQuestion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuizQuestionUpsert) {
//			SetQuizID(v+v).
//		}).
//		Exec(ctx)
func (qqcb *QuizQuestionCreateBulk) OnConflict(opts ...sql.ConflictOption) *QuizQuestionUpsertBulk {
	qqcb.conflict = opts
	return &QuizQuestionUpsertBulk{
		create: qqcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.QuizQuestion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (qqcb *QuizQuestionCreateBulk) OnConflictColumns(columns ...string) *QuizQuestionUpsertBulk {
	qqcb.conflict = append(qqcb.conflict, sql.ConflictColumns(columns...))
	return &QuizQuestionUpsertBulk{
		create: qqcb,
	}
}

// QuizQuestionUpsertBulk is the builder for "upsert"-ing
// a bulk of QuizQuestion nodes.
type QuizQuestionUpsertBulk struct {
	create *QuizQuestionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.QuizQuestion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *QuizQuestionUpsertBulk) UpdateNewValues() *QuizQuestionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.QuizQuestion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *QuizQuestionUpsertBulk) Ignore() *QuizQuestionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuizQuestionUpsertBulk) DoNothing() *QuizQuestionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuizQuestionCreateBulk.OnConflict
// documentation for more info.
func (u *QuizQuestionUpsertBulk) Update(set func(*QuizQuestionUpsert)) *QuizQuestionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuizQuestionUpsert{UpdateSet: update})
	}))
	return u
}

// SetQuizID sets the "quiz_id" field.
func (u *QuizQuestionUpsertBulk) SetQuizID(v int) *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetQuizID(v)
	})
}

// UpdateQuizID sets the "quiz_id" field to the value that was provided on create.
func (u *QuizQuestionUpsertBulk) UpdateQuizID() *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateQuizID()
	})
}

// SetQuestionNumber sets the "question_number" field.
func (u *QuizQuestionUpsertBulk) SetQuestionNumber(v int) *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetQuestionNumber(v)
	})
}

// AddQuestionNumber adds v to the "question_number" field.
func (u *QuizQuestionUpsertBulk) AddQuestionNumber(v int) *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.AddQuestionNumber(v)
	})
}

// UpdateQuestionNumber sets the "question_number" field to the value that was provided on create.
func (u *QuizQuestionUpsertBulk) UpdateQuestionNumber() *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateQuestionNumber()
	})
}

// SetWordID sets the "word_id" field.
func (u *QuizQuestionUpsertBulk) SetWordID(v int) *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetWordID(v)
	})
}

// UpdateWordID sets the "word_id" field to the value that was provided on create.
func (u *QuizQuestionUpsertBulk) UpdateWordID() *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateWordID()
	})
}

// SetCorrectJpmID sets the "correct_jpm_id" field.
func (u *QuizQuestionUpsertBulk) SetCorrectJpmID(v int) *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetCorrectJpmID(v)
	})
}

// UpdateCorrectJpmID sets the "correct_jpm_id" field to the value that was provided on create.
func (u *QuizQuestionUpsertBulk) UpdateCorrectJpmID() *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateCorrectJpmID()
	})
}

// SetChoicesJpmIds sets the "choices_jpm_ids" field.
func (u *QuizQuestionUpsertBulk) SetChoicesJpmIds(v []int) *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetChoicesJpmIds(v)
	})
}

// UpdateChoicesJpmIds sets the "choices_jpm_ids" field to the value that was provided on create.
func (u *QuizQuestionUpsertBulk) UpdateChoicesJpmIds() *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateChoicesJpmIds()
	})
}

// SetAnswerJpmID sets the "answer_jpm_id" field.
func (u *QuizQuestionUpsertBulk) SetAnswerJpmID(v int) *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetAnswerJpmID(v)
	})
}

// AddAnswerJpmID adds v to the "answer_jpm_id" field.
func (u *QuizQuestionUpsertBulk) AddAnswerJpmID(v int) *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.AddAnswerJpmID(v)
	})
}

// UpdateAnswerJpmID sets the "answer_jpm_id" field to the value that was provided on create.
func (u *QuizQuestionUpsertBulk) UpdateAnswerJpmID() *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateAnswerJpmID()
	})
}

// SetIsCorrect sets the "is_correct" field.
func (u *QuizQuestionUpsertBulk) SetIsCorrect(v bool) *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetIsCorrect(v)
	})
}

// UpdateIsCorrect sets the "is_correct" field to the value that was provided on create.
func (u *QuizQuestionUpsertBulk) UpdateIsCorrect() *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateIsCorrect()
	})
}

// SetAnsweredAt sets the "answered_at" field.
func (u *QuizQuestionUpsertBulk) SetAnsweredAt(v time.Time) *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetAnsweredAt(v)
	})
}

// UpdateAnsweredAt sets the "answered_at" field to the value that was provided on create.
func (u *QuizQuestionUpsertBulk) UpdateAnsweredAt() *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateAnsweredAt()
	})
}

// SetTimeMs sets the "time_ms" field.
func (u *QuizQuestionUpsertBulk) SetTimeMs(v int) *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetTimeMs(v)
	})
}

// AddTimeMs adds v to the "time_ms" field.
func (u *QuizQuestionUpsertBulk) AddTimeMs(v int) *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.AddTimeMs(v)
	})
}

// UpdateTimeMs sets the "time_ms" field to the value that was provided on create.
func (u *QuizQuestionUpsertBulk) UpdateTimeMs() *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateTimeMs()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *QuizQuestionUpsertBulk) SetCreatedAt(v time.Time) *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *QuizQuestionUpsertBulk) UpdateCreatedAt() *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *QuizQuestionUpsertBulk) SetDeletedAt(v time.Time) *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *QuizQuestionUpsertBulk) UpdateDeletedAt() *QuizQuestionUpsertBulk {
	return u.Update(func(s *QuizQuestionUpsert) {
		s.UpdateDeletedAt()
	})
}

// Exec executes the query.
func (u *QuizQuestionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the QuizQuestionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuizQuestionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuizQuestionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
