// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"word_app/backend/ent/japanesemean"
	"word_app/backend/ent/predicate"
	"word_app/backend/ent/quiz"
	"word_app/backend/ent/quizquestion"
	"word_app/backend/ent/word"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuizQuestionQuery is the builder for querying QuizQuestion entities.
type QuizQuestionQuery struct {
	config
	ctx              *QueryContext
	order            []quizquestion.OrderOption
	inters           []Interceptor
	predicates       []predicate.QuizQuestion
	withQuiz         *QuizQuery
	withWord         *WordQuery
	withJapaneseMean *JapaneseMeanQuery
	withFKs          bool
	modifiers        []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QuizQuestionQuery builder.
func (qqq *QuizQuestionQuery) Where(ps ...predicate.QuizQuestion) *QuizQuestionQuery {
	qqq.predicates = append(qqq.predicates, ps...)
	return qqq
}

// Limit the number of records to be returned by this query.
func (qqq *QuizQuestionQuery) Limit(limit int) *QuizQuestionQuery {
	qqq.ctx.Limit = &limit
	return qqq
}

// Offset to start from.
func (qqq *QuizQuestionQuery) Offset(offset int) *QuizQuestionQuery {
	qqq.ctx.Offset = &offset
	return qqq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (qqq *QuizQuestionQuery) Unique(unique bool) *QuizQuestionQuery {
	qqq.ctx.Unique = &unique
	return qqq
}

// Order specifies how the records should be ordered.
func (qqq *QuizQuestionQuery) Order(o ...quizquestion.OrderOption) *QuizQuestionQuery {
	qqq.order = append(qqq.order, o...)
	return qqq
}

// QueryQuiz chains the current query on the "quiz" edge.
func (qqq *QuizQuestionQuery) QueryQuiz() *QuizQuery {
	query := (&QuizClient{config: qqq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := qqq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := qqq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quizquestion.Table, quizquestion.FieldID, selector),
			sqlgraph.To(quiz.Table, quiz.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, quizquestion.QuizTable, quizquestion.QuizColumn),
		)
		fromU = sqlgraph.SetNeighbors(qqq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWord chains the current query on the "word" edge.
func (qqq *QuizQuestionQuery) QueryWord() *WordQuery {
	query := (&WordClient{config: qqq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := qqq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := qqq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quizquestion.Table, quizquestion.FieldID, selector),
			sqlgraph.To(word.Table, word.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, quizquestion.WordTable, quizquestion.WordColumn),
		)
		fromU = sqlgraph.SetNeighbors(qqq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryJapaneseMean chains the current query on the "japanese_mean" edge.
func (qqq *QuizQuestionQuery) QueryJapaneseMean() *JapaneseMeanQuery {
	query := (&JapaneseMeanClient{config: qqq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := qqq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := qqq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quizquestion.Table, quizquestion.FieldID, selector),
			sqlgraph.To(japanesemean.Table, japanesemean.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, quizquestion.JapaneseMeanTable, quizquestion.JapaneseMeanColumn),
		)
		fromU = sqlgraph.SetNeighbors(qqq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first QuizQuestion entity from the query.
// Returns a *NotFoundError when no QuizQuestion was found.
func (qqq *QuizQuestionQuery) First(ctx context.Context) (*QuizQuestion, error) {
	nodes, err := qqq.Limit(1).All(setContextOp(ctx, qqq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{quizquestion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (qqq *QuizQuestionQuery) FirstX(ctx context.Context) *QuizQuestion {
	node, err := qqq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first QuizQuestion ID from the query.
// Returns a *NotFoundError when no QuizQuestion ID was found.
func (qqq *QuizQuestionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = qqq.Limit(1).IDs(setContextOp(ctx, qqq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{quizquestion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (qqq *QuizQuestionQuery) FirstIDX(ctx context.Context) int {
	id, err := qqq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single QuizQuestion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one QuizQuestion entity is found.
// Returns a *NotFoundError when no QuizQuestion entities are found.
func (qqq *QuizQuestionQuery) Only(ctx context.Context) (*QuizQuestion, error) {
	nodes, err := qqq.Limit(2).All(setContextOp(ctx, qqq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{quizquestion.Label}
	default:
		return nil, &NotSingularError{quizquestion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (qqq *QuizQuestionQuery) OnlyX(ctx context.Context) *QuizQuestion {
	node, err := qqq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only QuizQuestion ID in the query.
// Returns a *NotSingularError when more than one QuizQuestion ID is found.
// Returns a *NotFoundError when no entities are found.
func (qqq *QuizQuestionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = qqq.Limit(2).IDs(setContextOp(ctx, qqq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{quizquestion.Label}
	default:
		err = &NotSingularError{quizquestion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (qqq *QuizQuestionQuery) OnlyIDX(ctx context.Context) int {
	id, err := qqq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of QuizQuestions.
func (qqq *QuizQuestionQuery) All(ctx context.Context) ([]*QuizQuestion, error) {
	ctx = setContextOp(ctx, qqq.ctx, ent.OpQueryAll)
	if err := qqq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*QuizQuestion, *QuizQuestionQuery]()
	return withInterceptors[[]*QuizQuestion](ctx, qqq, qr, qqq.inters)
}

// AllX is like All, but panics if an error occurs.
func (qqq *QuizQuestionQuery) AllX(ctx context.Context) []*QuizQuestion {
	nodes, err := qqq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of QuizQuestion IDs.
func (qqq *QuizQuestionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if qqq.ctx.Unique == nil && qqq.path != nil {
		qqq.Unique(true)
	}
	ctx = setContextOp(ctx, qqq.ctx, ent.OpQueryIDs)
	if err = qqq.Select(quizquestion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (qqq *QuizQuestionQuery) IDsX(ctx context.Context) []int {
	ids, err := qqq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (qqq *QuizQuestionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, qqq.ctx, ent.OpQueryCount)
	if err := qqq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, qqq, querierCount[*QuizQuestionQuery](), qqq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (qqq *QuizQuestionQuery) CountX(ctx context.Context) int {
	count, err := qqq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (qqq *QuizQuestionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, qqq.ctx, ent.OpQueryExist)
	switch _, err := qqq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (qqq *QuizQuestionQuery) ExistX(ctx context.Context) bool {
	exist, err := qqq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QuizQuestionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (qqq *QuizQuestionQuery) Clone() *QuizQuestionQuery {
	if qqq == nil {
		return nil
	}
	return &QuizQuestionQuery{
		config:           qqq.config,
		ctx:              qqq.ctx.Clone(),
		order:            append([]quizquestion.OrderOption{}, qqq.order...),
		inters:           append([]Interceptor{}, qqq.inters...),
		predicates:       append([]predicate.QuizQuestion{}, qqq.predicates...),
		withQuiz:         qqq.withQuiz.Clone(),
		withWord:         qqq.withWord.Clone(),
		withJapaneseMean: qqq.withJapaneseMean.Clone(),
		// clone intermediate query.
		sql:       qqq.sql.Clone(),
		path:      qqq.path,
		modifiers: append([]func(*sql.Selector){}, qqq.modifiers...),
	}
}

// WithQuiz tells the query-builder to eager-load the nodes that are connected to
// the "quiz" edge. The optional arguments are used to configure the query builder of the edge.
func (qqq *QuizQuestionQuery) WithQuiz(opts ...func(*QuizQuery)) *QuizQuestionQuery {
	query := (&QuizClient{config: qqq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	qqq.withQuiz = query
	return qqq
}

// WithWord tells the query-builder to eager-load the nodes that are connected to
// the "word" edge. The optional arguments are used to configure the query builder of the edge.
func (qqq *QuizQuestionQuery) WithWord(opts ...func(*WordQuery)) *QuizQuestionQuery {
	query := (&WordClient{config: qqq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	qqq.withWord = query
	return qqq
}

// WithJapaneseMean tells the query-builder to eager-load the nodes that are connected to
// the "japanese_mean" edge. The optional arguments are used to configure the query builder of the edge.
func (qqq *QuizQuestionQuery) WithJapaneseMean(opts ...func(*JapaneseMeanQuery)) *QuizQuestionQuery {
	query := (&JapaneseMeanClient{config: qqq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	qqq.withJapaneseMean = query
	return qqq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		QuizID int `json:"quiz_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.QuizQuestion.Query().
//		GroupBy(quizquestion.FieldQuizID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (qqq *QuizQuestionQuery) GroupBy(field string, fields ...string) *QuizQuestionGroupBy {
	qqq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &QuizQuestionGroupBy{build: qqq}
	grbuild.flds = &qqq.ctx.Fields
	grbuild.label = quizquestion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		QuizID int `json:"quiz_id,omitempty"`
//	}
//
//	client.QuizQuestion.Query().
//		Select(quizquestion.FieldQuizID).
//		Scan(ctx, &v)
func (qqq *QuizQuestionQuery) Select(fields ...string) *QuizQuestionSelect {
	qqq.ctx.Fields = append(qqq.ctx.Fields, fields...)
	sbuild := &QuizQuestionSelect{QuizQuestionQuery: qqq}
	sbuild.label = quizquestion.Label
	sbuild.flds, sbuild.scan = &qqq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a QuizQuestionSelect configured with the given aggregations.
func (qqq *QuizQuestionQuery) Aggregate(fns ...AggregateFunc) *QuizQuestionSelect {
	return qqq.Select().Aggregate(fns...)
}

func (qqq *QuizQuestionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range qqq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, qqq); err != nil {
				return err
			}
		}
	}
	for _, f := range qqq.ctx.Fields {
		if !quizquestion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if qqq.path != nil {
		prev, err := qqq.path(ctx)
		if err != nil {
			return err
		}
		qqq.sql = prev
	}
	return nil
}

func (qqq *QuizQuestionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*QuizQuestion, error) {
	var (
		nodes       = []*QuizQuestion{}
		withFKs     = qqq.withFKs
		_spec       = qqq.querySpec()
		loadedTypes = [3]bool{
			qqq.withQuiz != nil,
			qqq.withWord != nil,
			qqq.withJapaneseMean != nil,
		}
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, quizquestion.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*QuizQuestion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &QuizQuestion{config: qqq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(qqq.modifiers) > 0 {
		_spec.Modifiers = qqq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, qqq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := qqq.withQuiz; query != nil {
		if err := qqq.loadQuiz(ctx, query, nodes, nil,
			func(n *QuizQuestion, e *Quiz) { n.Edges.Quiz = e }); err != nil {
			return nil, err
		}
	}
	if query := qqq.withWord; query != nil {
		if err := qqq.loadWord(ctx, query, nodes, nil,
			func(n *QuizQuestion, e *Word) { n.Edges.Word = e }); err != nil {
			return nil, err
		}
	}
	if query := qqq.withJapaneseMean; query != nil {
		if err := qqq.loadJapaneseMean(ctx, query, nodes, nil,
			func(n *QuizQuestion, e *JapaneseMean) { n.Edges.JapaneseMean = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (qqq *QuizQuestionQuery) loadQuiz(ctx context.Context, query *QuizQuery, nodes []*QuizQuestion, init func(*QuizQuestion), assign func(*QuizQuestion, *Quiz)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*QuizQuestion)
	for i := range nodes {
		fk := nodes[i].QuizID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(quiz.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "quiz_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (qqq *QuizQuestionQuery) loadWord(ctx context.Context, query *WordQuery, nodes []*QuizQuestion, init func(*QuizQuestion), assign func(*QuizQuestion, *Word)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*QuizQuestion)
	for i := range nodes {
		fk := nodes[i].WordID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(word.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "word_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (qqq *QuizQuestionQuery) loadJapaneseMean(ctx context.Context, query *JapaneseMeanQuery, nodes []*QuizQuestion, init func(*QuizQuestion), assign func(*QuizQuestion, *JapaneseMean)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*QuizQuestion)
	for i := range nodes {
		fk := nodes[i].CorrectJpmID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(japanesemean.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "correct_jpm_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (qqq *QuizQuestionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := qqq.querySpec()
	if len(qqq.modifiers) > 0 {
		_spec.Modifiers = qqq.modifiers
	}
	_spec.Node.Columns = qqq.ctx.Fields
	if len(qqq.ctx.Fields) > 0 {
		_spec.Unique = qqq.ctx.Unique != nil && *qqq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, qqq.driver, _spec)
}

func (qqq *QuizQuestionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(quizquestion.Table, quizquestion.Columns, sqlgraph.NewFieldSpec(quizquestion.FieldID, field.TypeInt))
	_spec.From = qqq.sql
	if unique := qqq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if qqq.path != nil {
		_spec.Unique = true
	}
	if fields := qqq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quizquestion.FieldID)
		for i := range fields {
			if fields[i] != quizquestion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if qqq.withQuiz != nil {
			_spec.Node.AddColumnOnce(quizquestion.FieldQuizID)
		}
		if qqq.withWord != nil {
			_spec.Node.AddColumnOnce(quizquestion.FieldWordID)
		}
		if qqq.withJapaneseMean != nil {
			_spec.Node.AddColumnOnce(quizquestion.FieldCorrectJpmID)
		}
	}
	if ps := qqq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := qqq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := qqq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := qqq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (qqq *QuizQuestionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(qqq.driver.Dialect())
	t1 := builder.Table(quizquestion.Table)
	columns := qqq.ctx.Fields
	if len(columns) == 0 {
		columns = quizquestion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if qqq.sql != nil {
		selector = qqq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if qqq.ctx.Unique != nil && *qqq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range qqq.modifiers {
		m(selector)
	}
	for _, p := range qqq.predicates {
		p(selector)
	}
	for _, p := range qqq.order {
		p(selector)
	}
	if offset := qqq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := qqq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (qqq *QuizQuestionQuery) Modify(modifiers ...func(s *sql.Selector)) *QuizQuestionSelect {
	qqq.modifiers = append(qqq.modifiers, modifiers...)
	return qqq.Select()
}

// QuizQuestionGroupBy is the group-by builder for QuizQuestion entities.
type QuizQuestionGroupBy struct {
	selector
	build *QuizQuestionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (qqgb *QuizQuestionGroupBy) Aggregate(fns ...AggregateFunc) *QuizQuestionGroupBy {
	qqgb.fns = append(qqgb.fns, fns...)
	return qqgb
}

// Scan applies the selector query and scans the result into the given value.
func (qqgb *QuizQuestionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qqgb.build.ctx, ent.OpQueryGroupBy)
	if err := qqgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuizQuestionQuery, *QuizQuestionGroupBy](ctx, qqgb.build, qqgb, qqgb.build.inters, v)
}

func (qqgb *QuizQuestionGroupBy) sqlScan(ctx context.Context, root *QuizQuestionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(qqgb.fns))
	for _, fn := range qqgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*qqgb.flds)+len(qqgb.fns))
		for _, f := range *qqgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*qqgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qqgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// QuizQuestionSelect is the builder for selecting fields of QuizQuestion entities.
type QuizQuestionSelect struct {
	*QuizQuestionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (qqs *QuizQuestionSelect) Aggregate(fns ...AggregateFunc) *QuizQuestionSelect {
	qqs.fns = append(qqs.fns, fns...)
	return qqs
}

// Scan applies the selector query and scans the result into the given value.
func (qqs *QuizQuestionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qqs.ctx, ent.OpQuerySelect)
	if err := qqs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuizQuestionQuery, *QuizQuestionSelect](ctx, qqs.QuizQuestionQuery, qqs, qqs.inters, v)
}

func (qqs *QuizQuestionSelect) sqlScan(ctx context.Context, root *QuizQuestionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(qqs.fns))
	for _, fn := range qqs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*qqs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qqs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (qqs *QuizQuestionSelect) Modify(modifiers ...func(s *sql.Selector)) *QuizQuestionSelect {
	qqs.modifiers = append(qqs.modifiers, modifiers...)
	return qqs
}
