// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"word_app/backend/ent/predicate"
	"word_app/backend/ent/quizquestion"
	"word_app/backend/ent/registeredword"
	"word_app/backend/ent/user"
	"word_app/backend/ent/word"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RegisteredWordQuery is the builder for querying RegisteredWord entities.
type RegisteredWordQuery struct {
	config
	ctx               *QueryContext
	order             []registeredword.OrderOption
	inters            []Interceptor
	predicates        []predicate.RegisteredWord
	withUser          *UserQuery
	withWord          *WordQuery
	withQuizQuestions *QuizQuestionQuery
	modifiers         []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RegisteredWordQuery builder.
func (rwq *RegisteredWordQuery) Where(ps ...predicate.RegisteredWord) *RegisteredWordQuery {
	rwq.predicates = append(rwq.predicates, ps...)
	return rwq
}

// Limit the number of records to be returned by this query.
func (rwq *RegisteredWordQuery) Limit(limit int) *RegisteredWordQuery {
	rwq.ctx.Limit = &limit
	return rwq
}

// Offset to start from.
func (rwq *RegisteredWordQuery) Offset(offset int) *RegisteredWordQuery {
	rwq.ctx.Offset = &offset
	return rwq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rwq *RegisteredWordQuery) Unique(unique bool) *RegisteredWordQuery {
	rwq.ctx.Unique = &unique
	return rwq
}

// Order specifies how the records should be ordered.
func (rwq *RegisteredWordQuery) Order(o ...registeredword.OrderOption) *RegisteredWordQuery {
	rwq.order = append(rwq.order, o...)
	return rwq
}

// QueryUser chains the current query on the "user" edge.
func (rwq *RegisteredWordQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: rwq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rwq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rwq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(registeredword.Table, registeredword.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, registeredword.UserTable, registeredword.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(rwq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWord chains the current query on the "word" edge.
func (rwq *RegisteredWordQuery) QueryWord() *WordQuery {
	query := (&WordClient{config: rwq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rwq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rwq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(registeredword.Table, registeredword.FieldID, selector),
			sqlgraph.To(word.Table, word.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, registeredword.WordTable, registeredword.WordColumn),
		)
		fromU = sqlgraph.SetNeighbors(rwq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryQuizQuestions chains the current query on the "quiz_questions" edge.
func (rwq *RegisteredWordQuery) QueryQuizQuestions() *QuizQuestionQuery {
	query := (&QuizQuestionClient{config: rwq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rwq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rwq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(registeredword.Table, registeredword.FieldID, selector),
			sqlgraph.To(quizquestion.Table, quizquestion.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, registeredword.QuizQuestionsTable, registeredword.QuizQuestionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(rwq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RegisteredWord entity from the query.
// Returns a *NotFoundError when no RegisteredWord was found.
func (rwq *RegisteredWordQuery) First(ctx context.Context) (*RegisteredWord, error) {
	nodes, err := rwq.Limit(1).All(setContextOp(ctx, rwq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{registeredword.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rwq *RegisteredWordQuery) FirstX(ctx context.Context) *RegisteredWord {
	node, err := rwq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RegisteredWord ID from the query.
// Returns a *NotFoundError when no RegisteredWord ID was found.
func (rwq *RegisteredWordQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rwq.Limit(1).IDs(setContextOp(ctx, rwq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{registeredword.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rwq *RegisteredWordQuery) FirstIDX(ctx context.Context) int {
	id, err := rwq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RegisteredWord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RegisteredWord entity is found.
// Returns a *NotFoundError when no RegisteredWord entities are found.
func (rwq *RegisteredWordQuery) Only(ctx context.Context) (*RegisteredWord, error) {
	nodes, err := rwq.Limit(2).All(setContextOp(ctx, rwq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{registeredword.Label}
	default:
		return nil, &NotSingularError{registeredword.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rwq *RegisteredWordQuery) OnlyX(ctx context.Context) *RegisteredWord {
	node, err := rwq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RegisteredWord ID in the query.
// Returns a *NotSingularError when more than one RegisteredWord ID is found.
// Returns a *NotFoundError when no entities are found.
func (rwq *RegisteredWordQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rwq.Limit(2).IDs(setContextOp(ctx, rwq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{registeredword.Label}
	default:
		err = &NotSingularError{registeredword.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rwq *RegisteredWordQuery) OnlyIDX(ctx context.Context) int {
	id, err := rwq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RegisteredWords.
func (rwq *RegisteredWordQuery) All(ctx context.Context) ([]*RegisteredWord, error) {
	ctx = setContextOp(ctx, rwq.ctx, ent.OpQueryAll)
	if err := rwq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RegisteredWord, *RegisteredWordQuery]()
	return withInterceptors[[]*RegisteredWord](ctx, rwq, qr, rwq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rwq *RegisteredWordQuery) AllX(ctx context.Context) []*RegisteredWord {
	nodes, err := rwq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RegisteredWord IDs.
func (rwq *RegisteredWordQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rwq.ctx.Unique == nil && rwq.path != nil {
		rwq.Unique(true)
	}
	ctx = setContextOp(ctx, rwq.ctx, ent.OpQueryIDs)
	if err = rwq.Select(registeredword.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rwq *RegisteredWordQuery) IDsX(ctx context.Context) []int {
	ids, err := rwq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rwq *RegisteredWordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rwq.ctx, ent.OpQueryCount)
	if err := rwq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rwq, querierCount[*RegisteredWordQuery](), rwq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rwq *RegisteredWordQuery) CountX(ctx context.Context) int {
	count, err := rwq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rwq *RegisteredWordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rwq.ctx, ent.OpQueryExist)
	switch _, err := rwq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rwq *RegisteredWordQuery) ExistX(ctx context.Context) bool {
	exist, err := rwq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RegisteredWordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rwq *RegisteredWordQuery) Clone() *RegisteredWordQuery {
	if rwq == nil {
		return nil
	}
	return &RegisteredWordQuery{
		config:            rwq.config,
		ctx:               rwq.ctx.Clone(),
		order:             append([]registeredword.OrderOption{}, rwq.order...),
		inters:            append([]Interceptor{}, rwq.inters...),
		predicates:        append([]predicate.RegisteredWord{}, rwq.predicates...),
		withUser:          rwq.withUser.Clone(),
		withWord:          rwq.withWord.Clone(),
		withQuizQuestions: rwq.withQuizQuestions.Clone(),
		// clone intermediate query.
		sql:       rwq.sql.Clone(),
		path:      rwq.path,
		modifiers: append([]func(*sql.Selector){}, rwq.modifiers...),
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (rwq *RegisteredWordQuery) WithUser(opts ...func(*UserQuery)) *RegisteredWordQuery {
	query := (&UserClient{config: rwq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rwq.withUser = query
	return rwq
}

// WithWord tells the query-builder to eager-load the nodes that are connected to
// the "word" edge. The optional arguments are used to configure the query builder of the edge.
func (rwq *RegisteredWordQuery) WithWord(opts ...func(*WordQuery)) *RegisteredWordQuery {
	query := (&WordClient{config: rwq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rwq.withWord = query
	return rwq
}

// WithQuizQuestions tells the query-builder to eager-load the nodes that are connected to
// the "quiz_questions" edge. The optional arguments are used to configure the query builder of the edge.
func (rwq *RegisteredWordQuery) WithQuizQuestions(opts ...func(*QuizQuestionQuery)) *RegisteredWordQuery {
	query := (&QuizQuestionClient{config: rwq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rwq.withQuizQuestions = query
	return rwq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RegisteredWord.Query().
//		GroupBy(registeredword.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rwq *RegisteredWordQuery) GroupBy(field string, fields ...string) *RegisteredWordGroupBy {
	rwq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RegisteredWordGroupBy{build: rwq}
	grbuild.flds = &rwq.ctx.Fields
	grbuild.label = registeredword.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.RegisteredWord.Query().
//		Select(registeredword.FieldUserID).
//		Scan(ctx, &v)
func (rwq *RegisteredWordQuery) Select(fields ...string) *RegisteredWordSelect {
	rwq.ctx.Fields = append(rwq.ctx.Fields, fields...)
	sbuild := &RegisteredWordSelect{RegisteredWordQuery: rwq}
	sbuild.label = registeredword.Label
	sbuild.flds, sbuild.scan = &rwq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RegisteredWordSelect configured with the given aggregations.
func (rwq *RegisteredWordQuery) Aggregate(fns ...AggregateFunc) *RegisteredWordSelect {
	return rwq.Select().Aggregate(fns...)
}

func (rwq *RegisteredWordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rwq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rwq); err != nil {
				return err
			}
		}
	}
	for _, f := range rwq.ctx.Fields {
		if !registeredword.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rwq.path != nil {
		prev, err := rwq.path(ctx)
		if err != nil {
			return err
		}
		rwq.sql = prev
	}
	return nil
}

func (rwq *RegisteredWordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RegisteredWord, error) {
	var (
		nodes       = []*RegisteredWord{}
		_spec       = rwq.querySpec()
		loadedTypes = [3]bool{
			rwq.withUser != nil,
			rwq.withWord != nil,
			rwq.withQuizQuestions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RegisteredWord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RegisteredWord{config: rwq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(rwq.modifiers) > 0 {
		_spec.Modifiers = rwq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rwq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rwq.withUser; query != nil {
		if err := rwq.loadUser(ctx, query, nodes, nil,
			func(n *RegisteredWord, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := rwq.withWord; query != nil {
		if err := rwq.loadWord(ctx, query, nodes, nil,
			func(n *RegisteredWord, e *Word) { n.Edges.Word = e }); err != nil {
			return nil, err
		}
	}
	if query := rwq.withQuizQuestions; query != nil {
		if err := rwq.loadQuizQuestions(ctx, query, nodes,
			func(n *RegisteredWord) { n.Edges.QuizQuestions = []*QuizQuestion{} },
			func(n *RegisteredWord, e *QuizQuestion) { n.Edges.QuizQuestions = append(n.Edges.QuizQuestions, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rwq *RegisteredWordQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*RegisteredWord, init func(*RegisteredWord), assign func(*RegisteredWord, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RegisteredWord)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (rwq *RegisteredWordQuery) loadWord(ctx context.Context, query *WordQuery, nodes []*RegisteredWord, init func(*RegisteredWord), assign func(*RegisteredWord, *Word)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RegisteredWord)
	for i := range nodes {
		fk := nodes[i].WordID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(word.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "word_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (rwq *RegisteredWordQuery) loadQuizQuestions(ctx context.Context, query *QuizQuestionQuery, nodes []*RegisteredWord, init func(*RegisteredWord), assign func(*RegisteredWord, *QuizQuestion)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*RegisteredWord)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.QuizQuestion(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(registeredword.QuizQuestionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.registered_word_quiz_questions
		if fk == nil {
			return fmt.Errorf(`foreign-key "registered_word_quiz_questions" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "registered_word_quiz_questions" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (rwq *RegisteredWordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rwq.querySpec()
	if len(rwq.modifiers) > 0 {
		_spec.Modifiers = rwq.modifiers
	}
	_spec.Node.Columns = rwq.ctx.Fields
	if len(rwq.ctx.Fields) > 0 {
		_spec.Unique = rwq.ctx.Unique != nil && *rwq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rwq.driver, _spec)
}

func (rwq *RegisteredWordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(registeredword.Table, registeredword.Columns, sqlgraph.NewFieldSpec(registeredword.FieldID, field.TypeInt))
	_spec.From = rwq.sql
	if unique := rwq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rwq.path != nil {
		_spec.Unique = true
	}
	if fields := rwq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, registeredword.FieldID)
		for i := range fields {
			if fields[i] != registeredword.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if rwq.withUser != nil {
			_spec.Node.AddColumnOnce(registeredword.FieldUserID)
		}
		if rwq.withWord != nil {
			_spec.Node.AddColumnOnce(registeredword.FieldWordID)
		}
	}
	if ps := rwq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rwq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rwq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rwq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rwq *RegisteredWordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rwq.driver.Dialect())
	t1 := builder.Table(registeredword.Table)
	columns := rwq.ctx.Fields
	if len(columns) == 0 {
		columns = registeredword.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rwq.sql != nil {
		selector = rwq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rwq.ctx.Unique != nil && *rwq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range rwq.modifiers {
		m(selector)
	}
	for _, p := range rwq.predicates {
		p(selector)
	}
	for _, p := range rwq.order {
		p(selector)
	}
	if offset := rwq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rwq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rwq *RegisteredWordQuery) Modify(modifiers ...func(s *sql.Selector)) *RegisteredWordSelect {
	rwq.modifiers = append(rwq.modifiers, modifiers...)
	return rwq.Select()
}

// RegisteredWordGroupBy is the group-by builder for RegisteredWord entities.
type RegisteredWordGroupBy struct {
	selector
	build *RegisteredWordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rwgb *RegisteredWordGroupBy) Aggregate(fns ...AggregateFunc) *RegisteredWordGroupBy {
	rwgb.fns = append(rwgb.fns, fns...)
	return rwgb
}

// Scan applies the selector query and scans the result into the given value.
func (rwgb *RegisteredWordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rwgb.build.ctx, ent.OpQueryGroupBy)
	if err := rwgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RegisteredWordQuery, *RegisteredWordGroupBy](ctx, rwgb.build, rwgb, rwgb.build.inters, v)
}

func (rwgb *RegisteredWordGroupBy) sqlScan(ctx context.Context, root *RegisteredWordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rwgb.fns))
	for _, fn := range rwgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rwgb.flds)+len(rwgb.fns))
		for _, f := range *rwgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rwgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rwgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RegisteredWordSelect is the builder for selecting fields of RegisteredWord entities.
type RegisteredWordSelect struct {
	*RegisteredWordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rws *RegisteredWordSelect) Aggregate(fns ...AggregateFunc) *RegisteredWordSelect {
	rws.fns = append(rws.fns, fns...)
	return rws
}

// Scan applies the selector query and scans the result into the given value.
func (rws *RegisteredWordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rws.ctx, ent.OpQuerySelect)
	if err := rws.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RegisteredWordQuery, *RegisteredWordSelect](ctx, rws.RegisteredWordQuery, rws, rws.inters, v)
}

func (rws *RegisteredWordSelect) sqlScan(ctx context.Context, root *RegisteredWordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rws.fns))
	for _, fn := range rws.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rws.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rws.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rws *RegisteredWordSelect) Modify(modifiers ...func(s *sql.Selector)) *RegisteredWordSelect {
	rws.modifiers = append(rws.modifiers, modifiers...)
	return rws
}
