// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"word_app/backend/ent/predicate"
	"word_app/backend/ent/rootconfig"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RootConfigDelete is the builder for deleting a RootConfig entity.
type RootConfigDelete struct {
	config
	hooks    []Hook
	mutation *RootConfigMutation
}

// Where appends a list predicates to the RootConfigDelete builder.
func (rcd *RootConfigDelete) Where(ps ...predicate.RootConfig) *RootConfigDelete {
	rcd.mutation.Where(ps...)
	return rcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rcd *RootConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rcd.sqlExec, rcd.mutation, rcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rcd *RootConfigDelete) ExecX(ctx context.Context) int {
	n, err := rcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rcd *RootConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(rootconfig.Table, sqlgraph.NewFieldSpec(rootconfig.FieldID, field.TypeInt))
	if ps := rcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rcd.mutation.done = true
	return affected, err
}

// RootConfigDeleteOne is the builder for deleting a single RootConfig entity.
type RootConfigDeleteOne struct {
	rcd *RootConfigDelete
}

// Where appends a list predicates to the RootConfigDelete builder.
func (rcdo *RootConfigDeleteOne) Where(ps ...predicate.RootConfig) *RootConfigDeleteOne {
	rcdo.rcd.mutation.Where(ps...)
	return rcdo
}

// Exec executes the deletion query.
func (rcdo *RootConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := rcdo.rcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rootconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rcdo *RootConfigDeleteOne) ExecX(ctx context.Context) {
	if err := rcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
