// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"word_app/backend/ent/rootconfig"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// RootConfig is the model entity for the RootConfig schema.
type RootConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// EditingPermission holds the value of the "editing_permission" field.
	EditingPermission string `json:"editing_permission,omitempty"`
	// IsTestUserMode holds the value of the "is_test_user_mode" field.
	IsTestUserMode bool `json:"is_test_user_mode"`
	// IsEmailAuthentication holds the value of the "is_email_authentication" field.
	IsEmailAuthentication bool `json:"is_email_authentication"`
	selectValues          sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RootConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rootconfig.FieldIsTestUserMode, rootconfig.FieldIsEmailAuthentication:
			values[i] = new(sql.NullBool)
		case rootconfig.FieldID:
			values[i] = new(sql.NullInt64)
		case rootconfig.FieldEditingPermission:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RootConfig fields.
func (rc *RootConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rootconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rc.ID = int(value.Int64)
		case rootconfig.FieldEditingPermission:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field editing_permission", values[i])
			} else if value.Valid {
				rc.EditingPermission = value.String
			}
		case rootconfig.FieldIsTestUserMode:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_test_user_mode", values[i])
			} else if value.Valid {
				rc.IsTestUserMode = value.Bool
			}
		case rootconfig.FieldIsEmailAuthentication:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_email_authentication", values[i])
			} else if value.Valid {
				rc.IsEmailAuthentication = value.Bool
			}
		default:
			rc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RootConfig.
// This includes values selected through modifiers, order, etc.
func (rc *RootConfig) Value(name string) (ent.Value, error) {
	return rc.selectValues.Get(name)
}

// Update returns a builder for updating this RootConfig.
// Note that you need to call RootConfig.Unwrap() before calling this method if this RootConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (rc *RootConfig) Update() *RootConfigUpdateOne {
	return NewRootConfigClient(rc.config).UpdateOne(rc)
}

// Unwrap unwraps the RootConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rc *RootConfig) Unwrap() *RootConfig {
	_tx, ok := rc.config.driver.(*txDriver)
	if !ok {
		panic("ent: RootConfig is not a transactional entity")
	}
	rc.config.driver = _tx.drv
	return rc
}

// String implements the fmt.Stringer.
func (rc *RootConfig) String() string {
	var builder strings.Builder
	builder.WriteString("RootConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rc.ID))
	builder.WriteString("editing_permission=")
	builder.WriteString(rc.EditingPermission)
	builder.WriteString(", ")
	builder.WriteString("is_test_user_mode=")
	builder.WriteString(fmt.Sprintf("%v", rc.IsTestUserMode))
	builder.WriteString(", ")
	builder.WriteString("is_email_authentication=")
	builder.WriteString(fmt.Sprintf("%v", rc.IsEmailAuthentication))
	builder.WriteByte(')')
	return builder.String()
}

// RootConfigs is a parsable slice of RootConfig.
type RootConfigs []*RootConfig
