// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"word_app/backend/ent/japanesemean"
	"word_app/backend/ent/partofspeech"
	"word_app/backend/ent/registeredword"
	"word_app/backend/ent/rootconfig"
	"word_app/backend/ent/schema"
	"word_app/backend/ent/test"
	"word_app/backend/ent/testquestion"
	"word_app/backend/ent/user"
	"word_app/backend/ent/word"
	"word_app/backend/ent/wordinfo"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	japanesemeanFields := schema.JapaneseMean{}.Fields()
	_ = japanesemeanFields
	// japanesemeanDescName is the schema descriptor for name field.
	japanesemeanDescName := japanesemeanFields[0].Descriptor()
	// japanesemean.NameValidator is a validator for the "name" field. It is called by the builders before save.
	japanesemean.NameValidator = func() func(string) error {
		validators := japanesemeanDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// japanesemeanDescWordInfoID is the schema descriptor for word_info_id field.
	japanesemeanDescWordInfoID := japanesemeanFields[1].Descriptor()
	// japanesemean.WordInfoIDValidator is a validator for the "word_info_id" field. It is called by the builders before save.
	japanesemean.WordInfoIDValidator = japanesemeanDescWordInfoID.Validators[0].(func(int) error)
	// japanesemeanDescCreatedAt is the schema descriptor for created_at field.
	japanesemeanDescCreatedAt := japanesemeanFields[2].Descriptor()
	// japanesemean.DefaultCreatedAt holds the default value on creation for the created_at field.
	japanesemean.DefaultCreatedAt = japanesemeanDescCreatedAt.Default.(func() time.Time)
	// japanesemeanDescUpdatedAt is the schema descriptor for updated_at field.
	japanesemeanDescUpdatedAt := japanesemeanFields[3].Descriptor()
	// japanesemean.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	japanesemean.DefaultUpdatedAt = japanesemeanDescUpdatedAt.Default.(func() time.Time)
	// japanesemean.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	japanesemean.UpdateDefaultUpdatedAt = japanesemeanDescUpdatedAt.UpdateDefault.(func() time.Time)
	partofspeechFields := schema.PartOfSpeech{}.Fields()
	_ = partofspeechFields
	// partofspeechDescName is the schema descriptor for name field.
	partofspeechDescName := partofspeechFields[0].Descriptor()
	// partofspeech.NameValidator is a validator for the "name" field. It is called by the builders before save.
	partofspeech.NameValidator = partofspeechDescName.Validators[0].(func(string) error)
	// partofspeechDescCreatedAt is the schema descriptor for created_at field.
	partofspeechDescCreatedAt := partofspeechFields[1].Descriptor()
	// partofspeech.DefaultCreatedAt holds the default value on creation for the created_at field.
	partofspeech.DefaultCreatedAt = partofspeechDescCreatedAt.Default.(func() time.Time)
	// partofspeechDescUpdatedAt is the schema descriptor for updated_at field.
	partofspeechDescUpdatedAt := partofspeechFields[2].Descriptor()
	// partofspeech.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	partofspeech.DefaultUpdatedAt = partofspeechDescUpdatedAt.Default.(func() time.Time)
	// partofspeech.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	partofspeech.UpdateDefaultUpdatedAt = partofspeechDescUpdatedAt.UpdateDefault.(func() time.Time)
	registeredwordFields := schema.RegisteredWord{}.Fields()
	_ = registeredwordFields
	// registeredwordDescUserID is the schema descriptor for user_id field.
	registeredwordDescUserID := registeredwordFields[0].Descriptor()
	// registeredword.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	registeredword.UserIDValidator = registeredwordDescUserID.Validators[0].(func(int) error)
	// registeredwordDescIsActive is the schema descriptor for is_active field.
	registeredwordDescIsActive := registeredwordFields[2].Descriptor()
	// registeredword.DefaultIsActive holds the default value on creation for the is_active field.
	registeredword.DefaultIsActive = registeredwordDescIsActive.Default.(bool)
	// registeredwordDescAttentionLevel is the schema descriptor for attention_level field.
	registeredwordDescAttentionLevel := registeredwordFields[3].Descriptor()
	// registeredword.DefaultAttentionLevel holds the default value on creation for the attention_level field.
	registeredword.DefaultAttentionLevel = registeredwordDescAttentionLevel.Default.(int)
	// registeredword.AttentionLevelValidator is a validator for the "attention_level" field. It is called by the builders before save.
	registeredword.AttentionLevelValidator = registeredwordDescAttentionLevel.Validators[0].(func(int) error)
	// registeredwordDescTestCount is the schema descriptor for test_count field.
	registeredwordDescTestCount := registeredwordFields[4].Descriptor()
	// registeredword.DefaultTestCount holds the default value on creation for the test_count field.
	registeredword.DefaultTestCount = registeredwordDescTestCount.Default.(int)
	// registeredwordDescCheckCount is the schema descriptor for check_count field.
	registeredwordDescCheckCount := registeredwordFields[5].Descriptor()
	// registeredword.DefaultCheckCount holds the default value on creation for the check_count field.
	registeredword.DefaultCheckCount = registeredwordDescCheckCount.Default.(int)
	// registeredwordDescMemo is the schema descriptor for memo field.
	registeredwordDescMemo := registeredwordFields[6].Descriptor()
	// registeredword.MemoValidator is a validator for the "memo" field. It is called by the builders before save.
	registeredword.MemoValidator = registeredwordDescMemo.Validators[0].(func(string) error)
	// registeredwordDescCreatedAt is the schema descriptor for created_at field.
	registeredwordDescCreatedAt := registeredwordFields[7].Descriptor()
	// registeredword.DefaultCreatedAt holds the default value on creation for the created_at field.
	registeredword.DefaultCreatedAt = registeredwordDescCreatedAt.Default.(func() time.Time)
	// registeredwordDescUpdatedAt is the schema descriptor for updated_at field.
	registeredwordDescUpdatedAt := registeredwordFields[8].Descriptor()
	// registeredword.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	registeredword.DefaultUpdatedAt = registeredwordDescUpdatedAt.Default.(func() time.Time)
	// registeredword.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	registeredword.UpdateDefaultUpdatedAt = registeredwordDescUpdatedAt.UpdateDefault.(func() time.Time)
	rootconfigFields := schema.RootConfig{}.Fields()
	_ = rootconfigFields
	// rootconfigDescEditingPermission is the schema descriptor for editing_permission field.
	rootconfigDescEditingPermission := rootconfigFields[0].Descriptor()
	// rootconfig.DefaultEditingPermission holds the default value on creation for the editing_permission field.
	rootconfig.DefaultEditingPermission = rootconfigDescEditingPermission.Default.(int)
	testFields := schema.Test{}.Fields()
	_ = testFields
	// testDescTotalQuestions is the schema descriptor for total_questions field.
	testDescTotalQuestions := testFields[1].Descriptor()
	// test.DefaultTotalQuestions holds the default value on creation for the total_questions field.
	test.DefaultTotalQuestions = testDescTotalQuestions.Default.(int)
	// testDescCorrectCount is the schema descriptor for correct_count field.
	testDescCorrectCount := testFields[2].Descriptor()
	// test.DefaultCorrectCount holds the default value on creation for the correct_count field.
	test.DefaultCorrectCount = testDescCorrectCount.Default.(int)
	// testDescCreatedAt is the schema descriptor for created_at field.
	testDescCreatedAt := testFields[3].Descriptor()
	// test.DefaultCreatedAt holds the default value on creation for the created_at field.
	test.DefaultCreatedAt = testDescCreatedAt.Default.(func() time.Time)
	testquestionFields := schema.TestQuestion{}.Fields()
	_ = testquestionFields
	// testquestionDescIsCorrect is the schema descriptor for is_correct field.
	testquestionDescIsCorrect := testquestionFields[2].Descriptor()
	// testquestion.DefaultIsCorrect holds the default value on creation for the is_correct field.
	testquestion.DefaultIsCorrect = testquestionDescIsCorrect.Default.(bool)
	// testquestionDescCreatedAt is the schema descriptor for created_at field.
	testquestionDescCreatedAt := testquestionFields[3].Descriptor()
	// testquestion.DefaultCreatedAt holds the default value on creation for the created_at field.
	testquestion.DefaultCreatedAt = testquestionDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[1].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[2].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func() func(string) error {
		validators := userDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescAdmin is the schema descriptor for admin field.
	userDescAdmin := userFields[5].Descriptor()
	// user.DefaultAdmin holds the default value on creation for the admin field.
	user.DefaultAdmin = userDescAdmin.Default.(bool)
	// userDescRoot is the schema descriptor for root field.
	userDescRoot := userFields[6].Descriptor()
	// user.DefaultRoot holds the default value on creation for the root field.
	user.DefaultRoot = userDescRoot.Default.(bool)
	wordFields := schema.Word{}.Fields()
	_ = wordFields
	// wordDescName is the schema descriptor for name field.
	wordDescName := wordFields[0].Descriptor()
	// word.NameValidator is a validator for the "name" field. It is called by the builders before save.
	word.NameValidator = func() func(string) error {
		validators := wordDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// wordDescRegistrationCount is the schema descriptor for registration_count field.
	wordDescRegistrationCount := wordFields[2].Descriptor()
	// word.DefaultRegistrationCount holds the default value on creation for the registration_count field.
	word.DefaultRegistrationCount = wordDescRegistrationCount.Default.(int)
	// wordDescCreatedAt is the schema descriptor for created_at field.
	wordDescCreatedAt := wordFields[3].Descriptor()
	// word.DefaultCreatedAt holds the default value on creation for the created_at field.
	word.DefaultCreatedAt = wordDescCreatedAt.Default.(func() time.Time)
	// wordDescUpdatedAt is the schema descriptor for updated_at field.
	wordDescUpdatedAt := wordFields[4].Descriptor()
	// word.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	word.DefaultUpdatedAt = wordDescUpdatedAt.Default.(func() time.Time)
	// word.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	word.UpdateDefaultUpdatedAt = wordDescUpdatedAt.UpdateDefault.(func() time.Time)
	wordinfoFields := schema.WordInfo{}.Fields()
	_ = wordinfoFields
	// wordinfoDescWordID is the schema descriptor for word_id field.
	wordinfoDescWordID := wordinfoFields[0].Descriptor()
	// wordinfo.WordIDValidator is a validator for the "word_id" field. It is called by the builders before save.
	wordinfo.WordIDValidator = wordinfoDescWordID.Validators[0].(func(int) error)
	// wordinfoDescPartOfSpeechID is the schema descriptor for part_of_speech_id field.
	wordinfoDescPartOfSpeechID := wordinfoFields[1].Descriptor()
	// wordinfo.PartOfSpeechIDValidator is a validator for the "part_of_speech_id" field. It is called by the builders before save.
	wordinfo.PartOfSpeechIDValidator = wordinfoDescPartOfSpeechID.Validators[0].(func(int) error)
	// wordinfoDescCreatedAt is the schema descriptor for created_at field.
	wordinfoDescCreatedAt := wordinfoFields[2].Descriptor()
	// wordinfo.DefaultCreatedAt holds the default value on creation for the created_at field.
	wordinfo.DefaultCreatedAt = wordinfoDescCreatedAt.Default.(func() time.Time)
	// wordinfoDescUpdatedAt is the schema descriptor for updated_at field.
	wordinfoDescUpdatedAt := wordinfoFields[3].Descriptor()
	// wordinfo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	wordinfo.DefaultUpdatedAt = wordinfoDescUpdatedAt.Default.(func() time.Time)
	// wordinfo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	wordinfo.UpdateDefaultUpdatedAt = wordinfoDescUpdatedAt.UpdateDefault.(func() time.Time)
}
