// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"word_app/ent/japanesemean"
	"word_app/ent/partofspeech"
	"word_app/ent/schema"
	"word_app/ent/user"
	"word_app/ent/word"
	"word_app/ent/wordinfo"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	japanesemeanFields := schema.JapaneseMean{}.Fields()
	_ = japanesemeanFields
	// japanesemeanDescName is the schema descriptor for name field.
	japanesemeanDescName := japanesemeanFields[0].Descriptor()
	// japanesemean.NameValidator is a validator for the "name" field. It is called by the builders before save.
	japanesemean.NameValidator = japanesemeanDescName.Validators[0].(func(string) error)
	// japanesemeanDescWordInfoID is the schema descriptor for word_info_id field.
	japanesemeanDescWordInfoID := japanesemeanFields[1].Descriptor()
	// japanesemean.WordInfoIDValidator is a validator for the "word_info_id" field. It is called by the builders before save.
	japanesemean.WordInfoIDValidator = japanesemeanDescWordInfoID.Validators[0].(func(int) error)
	// japanesemeanDescCreatedAt is the schema descriptor for created_at field.
	japanesemeanDescCreatedAt := japanesemeanFields[2].Descriptor()
	// japanesemean.DefaultCreatedAt holds the default value on creation for the created_at field.
	japanesemean.DefaultCreatedAt = japanesemeanDescCreatedAt.Default.(func() time.Time)
	// japanesemeanDescUpdatedAt is the schema descriptor for updated_at field.
	japanesemeanDescUpdatedAt := japanesemeanFields[3].Descriptor()
	// japanesemean.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	japanesemean.DefaultUpdatedAt = japanesemeanDescUpdatedAt.Default.(func() time.Time)
	// japanesemean.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	japanesemean.UpdateDefaultUpdatedAt = japanesemeanDescUpdatedAt.UpdateDefault.(func() time.Time)
	partofspeechFields := schema.PartOfSpeech{}.Fields()
	_ = partofspeechFields
	// partofspeechDescName is the schema descriptor for name field.
	partofspeechDescName := partofspeechFields[0].Descriptor()
	// partofspeech.NameValidator is a validator for the "name" field. It is called by the builders before save.
	partofspeech.NameValidator = partofspeechDescName.Validators[0].(func(string) error)
	// partofspeechDescCreatedAt is the schema descriptor for created_at field.
	partofspeechDescCreatedAt := partofspeechFields[1].Descriptor()
	// partofspeech.DefaultCreatedAt holds the default value on creation for the created_at field.
	partofspeech.DefaultCreatedAt = partofspeechDescCreatedAt.Default.(func() time.Time)
	// partofspeechDescUpdatedAt is the schema descriptor for updated_at field.
	partofspeechDescUpdatedAt := partofspeechFields[2].Descriptor()
	// partofspeech.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	partofspeech.DefaultUpdatedAt = partofspeechDescUpdatedAt.Default.(func() time.Time)
	// partofspeech.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	partofspeech.UpdateDefaultUpdatedAt = partofspeechDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[1].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[2].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	wordFields := schema.Word{}.Fields()
	_ = wordFields
	// wordDescName is the schema descriptor for name field.
	wordDescName := wordFields[0].Descriptor()
	// word.NameValidator is a validator for the "name" field. It is called by the builders before save.
	word.NameValidator = wordDescName.Validators[0].(func(string) error)
	// wordDescVoiceID is the schema descriptor for voice_id field.
	wordDescVoiceID := wordFields[1].Descriptor()
	// word.VoiceIDValidator is a validator for the "voice_id" field. It is called by the builders before save.
	word.VoiceIDValidator = wordDescVoiceID.Validators[0].(func(int) error)
	// wordDescCreatedAt is the schema descriptor for created_at field.
	wordDescCreatedAt := wordFields[2].Descriptor()
	// word.DefaultCreatedAt holds the default value on creation for the created_at field.
	word.DefaultCreatedAt = wordDescCreatedAt.Default.(func() time.Time)
	// wordDescUpdatedAt is the schema descriptor for updated_at field.
	wordDescUpdatedAt := wordFields[3].Descriptor()
	// word.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	word.DefaultUpdatedAt = wordDescUpdatedAt.Default.(func() time.Time)
	// word.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	word.UpdateDefaultUpdatedAt = wordDescUpdatedAt.UpdateDefault.(func() time.Time)
	wordinfoFields := schema.WordInfo{}.Fields()
	_ = wordinfoFields
	// wordinfoDescWordID is the schema descriptor for word_id field.
	wordinfoDescWordID := wordinfoFields[0].Descriptor()
	// wordinfo.WordIDValidator is a validator for the "word_id" field. It is called by the builders before save.
	wordinfo.WordIDValidator = wordinfoDescWordID.Validators[0].(func(int) error)
	// wordinfoDescPartOfSpeechID is the schema descriptor for part_of_speech_id field.
	wordinfoDescPartOfSpeechID := wordinfoFields[1].Descriptor()
	// wordinfo.PartOfSpeechIDValidator is a validator for the "part_of_speech_id" field. It is called by the builders before save.
	wordinfo.PartOfSpeechIDValidator = wordinfoDescPartOfSpeechID.Validators[0].(func(int) error)
	// wordinfoDescCreatedAt is the schema descriptor for created_at field.
	wordinfoDescCreatedAt := wordinfoFields[2].Descriptor()
	// wordinfo.DefaultCreatedAt holds the default value on creation for the created_at field.
	wordinfo.DefaultCreatedAt = wordinfoDescCreatedAt.Default.(func() time.Time)
	// wordinfoDescUpdatedAt is the schema descriptor for updated_at field.
	wordinfoDescUpdatedAt := wordinfoFields[3].Descriptor()
	// wordinfo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	wordinfo.DefaultUpdatedAt = wordinfoDescUpdatedAt.Default.(func() time.Time)
	// wordinfo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	wordinfo.UpdateDefaultUpdatedAt = wordinfoDescUpdatedAt.UpdateDefault.(func() time.Time)
}
