// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"word_app/ent/predicate"
	"word_app/ent/testquestion"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TestQuestionDelete is the builder for deleting a TestQuestion entity.
type TestQuestionDelete struct {
	config
	hooks    []Hook
	mutation *TestQuestionMutation
}

// Where appends a list predicates to the TestQuestionDelete builder.
func (tqd *TestQuestionDelete) Where(ps ...predicate.TestQuestion) *TestQuestionDelete {
	tqd.mutation.Where(ps...)
	return tqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tqd *TestQuestionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tqd.sqlExec, tqd.mutation, tqd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tqd *TestQuestionDelete) ExecX(ctx context.Context) int {
	n, err := tqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tqd *TestQuestionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(testquestion.Table, sqlgraph.NewFieldSpec(testquestion.FieldID, field.TypeInt))
	if ps := tqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tqd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tqd.mutation.done = true
	return affected, err
}

// TestQuestionDeleteOne is the builder for deleting a single TestQuestion entity.
type TestQuestionDeleteOne struct {
	tqd *TestQuestionDelete
}

// Where appends a list predicates to the TestQuestionDelete builder.
func (tqdo *TestQuestionDeleteOne) Where(ps ...predicate.TestQuestion) *TestQuestionDeleteOne {
	tqdo.tqd.mutation.Where(ps...)
	return tqdo
}

// Exec executes the deletion query.
func (tqdo *TestQuestionDeleteOne) Exec(ctx context.Context) error {
	n, err := tqdo.tqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{testquestion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tqdo *TestQuestionDeleteOne) ExecX(ctx context.Context) {
	if err := tqdo.Exec(ctx); err != nil {
		panic(err)
	}
}
