// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package word

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReadRepository creates a new instance of MockReadRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadRepository {
	mock := &MockReadRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReadRepository is an autogenerated mock type for the ReadRepository type
type MockReadRepository struct {
	mock.Mock
}

type MockReadRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadRepository) EXPECT() *MockReadRepository_Expecter {
	return &MockReadRepository_Expecter{mock: &_m.Mock}
}

// FindIDsByNames provides a mock function for the type MockReadRepository
func (_mock *MockReadRepository) FindIDsByNames(ctx context.Context, names []string) (map[string]int, error) {
	ret := _mock.Called(ctx, names)

	if len(ret) == 0 {
		panic("no return value specified for FindIDsByNames")
	}

	var r0 map[string]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string]int, error)); ok {
		return returnFunc(ctx, names)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string]int); ok {
		r0 = returnFunc(ctx, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, names)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadRepository_FindIDsByNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIDsByNames'
type MockReadRepository_FindIDsByNames_Call struct {
	*mock.Call
}

// FindIDsByNames is a helper method to define mock.On call
//   - ctx context.Context
//   - names []string
func (_e *MockReadRepository_Expecter) FindIDsByNames(ctx interface{}, names interface{}) *MockReadRepository_FindIDsByNames_Call {
	return &MockReadRepository_FindIDsByNames_Call{Call: _e.mock.On("FindIDsByNames", ctx, names)}
}

func (_c *MockReadRepository_FindIDsByNames_Call) Run(run func(ctx context.Context, names []string)) *MockReadRepository_FindIDsByNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReadRepository_FindIDsByNames_Call) Return(stringToInt map[string]int, err error) *MockReadRepository_FindIDsByNames_Call {
	_c.Call.Return(stringToInt, err)
	return _c
}

func (_c *MockReadRepository_FindIDsByNames_Call) RunAndReturn(run func(ctx context.Context, names []string) (map[string]int, error)) *MockReadRepository_FindIDsByNames_Call {
	_c.Call.Return(run)
	return _c
}
