// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package bulk

import (
	"context"

	"word_app/backend/src/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRegisterUsecase creates a new instance of MockRegisterUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegisterUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegisterUsecase {
	mock := &MockRegisterUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegisterUsecase is an autogenerated mock type for the RegisterUsecase type
type MockRegisterUsecase struct {
	mock.Mock
}

type MockRegisterUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegisterUsecase) EXPECT() *MockRegisterUsecase_Expecter {
	return &MockRegisterUsecase_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type MockRegisterUsecase
func (_mock *MockRegisterUsecase) Register(ctx context.Context, userID int, words []string) (*models.BulkRegisterResponse, error) {
	ret := _mock.Called(ctx, userID, words)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *models.BulkRegisterResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []string) (*models.BulkRegisterResponse, error)); ok {
		return returnFunc(ctx, userID, words)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []string) *models.BulkRegisterResponse); ok {
		r0 = returnFunc(ctx, userID, words)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BulkRegisterResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, []string) error); ok {
		r1 = returnFunc(ctx, userID, words)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegisterUsecase_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockRegisterUsecase_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - words []string
func (_e *MockRegisterUsecase_Expecter) Register(ctx interface{}, userID interface{}, words interface{}) *MockRegisterUsecase_Register_Call {
	return &MockRegisterUsecase_Register_Call{Call: _e.mock.On("Register", ctx, userID, words)}
}

func (_c *MockRegisterUsecase_Register_Call) Run(run func(ctx context.Context, userID int, words []string)) *MockRegisterUsecase_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRegisterUsecase_Register_Call) Return(bulkRegisterResponse *models.BulkRegisterResponse, err error) *MockRegisterUsecase_Register_Call {
	_c.Call.Return(bulkRegisterResponse, err)
	return _c
}

func (_c *MockRegisterUsecase_Register_Call) RunAndReturn(run func(ctx context.Context, userID int, words []string) (*models.BulkRegisterResponse, error)) *MockRegisterUsecase_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenizeUsecase creates a new instance of MockTokenizeUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenizeUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenizeUsecase {
	mock := &MockTokenizeUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenizeUsecase is an autogenerated mock type for the TokenizeUsecase type
type MockTokenizeUsecase struct {
	mock.Mock
}

type MockTokenizeUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenizeUsecase) EXPECT() *MockTokenizeUsecase_Expecter {
	return &MockTokenizeUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockTokenizeUsecase
func (_mock *MockTokenizeUsecase) Execute(ctx context.Context, userID int, text string) ([]string, []string, []string, error) {
	ret := _mock.Called(ctx, userID, text)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []string
	var r1 []string
	var r2 []string
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) ([]string, []string, []string, error)); ok {
		return returnFunc(ctx, userID, text)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) []string); ok {
		r0 = returnFunc(ctx, userID, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) []string); ok {
		r1 = returnFunc(ctx, userID, text)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, string) []string); ok {
		r2 = returnFunc(ctx, userID, text)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]string)
		}
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, int, string) error); ok {
		r3 = returnFunc(ctx, userID, text)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockTokenizeUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockTokenizeUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - text string
func (_e *MockTokenizeUsecase_Expecter) Execute(ctx interface{}, userID interface{}, text interface{}) *MockTokenizeUsecase_Execute_Call {
	return &MockTokenizeUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, text)}
}

func (_c *MockTokenizeUsecase_Execute_Call) Run(run func(ctx context.Context, userID int, text string)) *MockTokenizeUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenizeUsecase_Execute_Call) Return(cands []string, regs []string, notExist []string, err error) *MockTokenizeUsecase_Execute_Call {
	_c.Call.Return(cands, regs, notExist, err)
	return _c
}

func (_c *MockTokenizeUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, userID int, text string) ([]string, []string, []string, error)) *MockTokenizeUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
