// Code generated by ent, DO NOT EDIT.

package test

import (
	"time"

	"word_app/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Test {
	return predicate.Test(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Test {
	return predicate.Test(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Test {
	return predicate.Test(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Test {
	return predicate.Test(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Test {
	return predicate.Test(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Test {
	return predicate.Test(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Test {
	return predicate.Test(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Test {
	return predicate.Test(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Test {
	return predicate.Test(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.Test {
	return predicate.Test(sql.FieldEQ(FieldUserID, v))
}

// TotalQuestions applies equality check predicate on the "total_questions" field. It's identical to TotalQuestionsEQ.
func TotalQuestions(v int) predicate.Test {
	return predicate.Test(sql.FieldEQ(FieldTotalQuestions, v))
}

// CorrectCount applies equality check predicate on the "correct_count" field. It's identical to CorrectCountEQ.
func CorrectCount(v int) predicate.Test {
	return predicate.Test(sql.FieldEQ(FieldCorrectCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Test {
	return predicate.Test(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.Test {
	return predicate.Test(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.Test {
	return predicate.Test(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.Test {
	return predicate.Test(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.Test {
	return predicate.Test(sql.FieldNotIn(FieldUserID, vs...))
}

// TotalQuestionsEQ applies the EQ predicate on the "total_questions" field.
func TotalQuestionsEQ(v int) predicate.Test {
	return predicate.Test(sql.FieldEQ(FieldTotalQuestions, v))
}

// TotalQuestionsNEQ applies the NEQ predicate on the "total_questions" field.
func TotalQuestionsNEQ(v int) predicate.Test {
	return predicate.Test(sql.FieldNEQ(FieldTotalQuestions, v))
}

// TotalQuestionsIn applies the In predicate on the "total_questions" field.
func TotalQuestionsIn(vs ...int) predicate.Test {
	return predicate.Test(sql.FieldIn(FieldTotalQuestions, vs...))
}

// TotalQuestionsNotIn applies the NotIn predicate on the "total_questions" field.
func TotalQuestionsNotIn(vs ...int) predicate.Test {
	return predicate.Test(sql.FieldNotIn(FieldTotalQuestions, vs...))
}

// TotalQuestionsGT applies the GT predicate on the "total_questions" field.
func TotalQuestionsGT(v int) predicate.Test {
	return predicate.Test(sql.FieldGT(FieldTotalQuestions, v))
}

// TotalQuestionsGTE applies the GTE predicate on the "total_questions" field.
func TotalQuestionsGTE(v int) predicate.Test {
	return predicate.Test(sql.FieldGTE(FieldTotalQuestions, v))
}

// TotalQuestionsLT applies the LT predicate on the "total_questions" field.
func TotalQuestionsLT(v int) predicate.Test {
	return predicate.Test(sql.FieldLT(FieldTotalQuestions, v))
}

// TotalQuestionsLTE applies the LTE predicate on the "total_questions" field.
func TotalQuestionsLTE(v int) predicate.Test {
	return predicate.Test(sql.FieldLTE(FieldTotalQuestions, v))
}

// CorrectCountEQ applies the EQ predicate on the "correct_count" field.
func CorrectCountEQ(v int) predicate.Test {
	return predicate.Test(sql.FieldEQ(FieldCorrectCount, v))
}

// CorrectCountNEQ applies the NEQ predicate on the "correct_count" field.
func CorrectCountNEQ(v int) predicate.Test {
	return predicate.Test(sql.FieldNEQ(FieldCorrectCount, v))
}

// CorrectCountIn applies the In predicate on the "correct_count" field.
func CorrectCountIn(vs ...int) predicate.Test {
	return predicate.Test(sql.FieldIn(FieldCorrectCount, vs...))
}

// CorrectCountNotIn applies the NotIn predicate on the "correct_count" field.
func CorrectCountNotIn(vs ...int) predicate.Test {
	return predicate.Test(sql.FieldNotIn(FieldCorrectCount, vs...))
}

// CorrectCountGT applies the GT predicate on the "correct_count" field.
func CorrectCountGT(v int) predicate.Test {
	return predicate.Test(sql.FieldGT(FieldCorrectCount, v))
}

// CorrectCountGTE applies the GTE predicate on the "correct_count" field.
func CorrectCountGTE(v int) predicate.Test {
	return predicate.Test(sql.FieldGTE(FieldCorrectCount, v))
}

// CorrectCountLT applies the LT predicate on the "correct_count" field.
func CorrectCountLT(v int) predicate.Test {
	return predicate.Test(sql.FieldLT(FieldCorrectCount, v))
}

// CorrectCountLTE applies the LTE predicate on the "correct_count" field.
func CorrectCountLTE(v int) predicate.Test {
	return predicate.Test(sql.FieldLTE(FieldCorrectCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Test {
	return predicate.Test(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Test {
	return predicate.Test(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Test {
	return predicate.Test(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Test {
	return predicate.Test(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Test {
	return predicate.Test(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Test {
	return predicate.Test(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Test {
	return predicate.Test(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Test {
	return predicate.Test(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Test {
	return predicate.Test(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Test {
	return predicate.Test(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTestQuestions applies the HasEdge predicate on the "test_questions" edge.
func HasTestQuestions() predicate.Test {
	return predicate.Test(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TestQuestionsTable, TestQuestionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTestQuestionsWith applies the HasEdge predicate on the "test_questions" edge with a given conditions (other predicates).
func HasTestQuestionsWith(preds ...predicate.TestQuestion) predicate.Test {
	return predicate.Test(func(s *sql.Selector) {
		step := newTestQuestionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Test) predicate.Test {
	return predicate.Test(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Test) predicate.Test {
	return predicate.Test(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Test) predicate.Test {
	return predicate.Test(sql.NotPredicates(p))
}
