// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// JapaneseMeansColumns holds the columns for the "japanese_means" table.
	JapaneseMeansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "word_info_id", Type: field.TypeInt},
	}
	// JapaneseMeansTable holds the schema information for the "japanese_means" table.
	JapaneseMeansTable = &schema.Table{
		Name:       "japanese_means",
		Columns:    JapaneseMeansColumns,
		PrimaryKey: []*schema.Column{JapaneseMeansColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "japanese_means_word_infos_japanese_means",
				Columns:    []*schema.Column{JapaneseMeansColumns[4]},
				RefColumns: []*schema.Column{WordInfosColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PartOfSpeechesColumns holds the columns for the "part_of_speeches" table.
	PartOfSpeechesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PartOfSpeechesTable holds the schema information for the "part_of_speeches" table.
	PartOfSpeechesTable = &schema.Table{
		Name:       "part_of_speeches",
		Columns:    PartOfSpeechesColumns,
		PrimaryKey: []*schema.Column{PartOfSpeechesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// WordsColumns holds the columns for the "words" table.
	WordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "voice_id", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// WordsTable holds the schema information for the "words" table.
	WordsTable = &schema.Table{
		Name:       "words",
		Columns:    WordsColumns,
		PrimaryKey: []*schema.Column{WordsColumns[0]},
	}
	// WordInfosColumns holds the columns for the "word_infos" table.
	WordInfosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "part_of_speech_id", Type: field.TypeInt},
		{Name: "word_id", Type: field.TypeInt},
	}
	// WordInfosTable holds the schema information for the "word_infos" table.
	WordInfosTable = &schema.Table{
		Name:       "word_infos",
		Columns:    WordInfosColumns,
		PrimaryKey: []*schema.Column{WordInfosColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "word_infos_part_of_speeches_word_infos",
				Columns:    []*schema.Column{WordInfosColumns[3]},
				RefColumns: []*schema.Column{PartOfSpeechesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "word_infos_words_word_infos",
				Columns:    []*schema.Column{WordInfosColumns[4]},
				RefColumns: []*schema.Column{WordsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		JapaneseMeansTable,
		PartOfSpeechesTable,
		UsersTable,
		WordsTable,
		WordInfosTable,
	}
)

func init() {
	JapaneseMeansTable.ForeignKeys[0].RefTable = WordInfosTable
	WordInfosTable.ForeignKeys[0].RefTable = PartOfSpeechesTable
	WordInfosTable.ForeignKeys[1].RefTable = WordsTable
}
