// Code generated by ent, DO NOT EDIT.

package examquestion

import (
	"time"
	"word_app/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldLTE(FieldID, id))
}

// ExamID applies equality check predicate on the "exam_id" field. It's identical to ExamIDEQ.
func ExamID(v int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldEQ(FieldExamID, v))
}

// CorrectJpmID applies equality check predicate on the "correct_jpm_id" field. It's identical to CorrectJpmIDEQ.
func CorrectJpmID(v int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldEQ(FieldCorrectJpmID, v))
}

// Answer applies equality check predicate on the "answer" field. It's identical to AnswerEQ.
func Answer(v string) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldEQ(FieldAnswer, v))
}

// IsCorrect applies equality check predicate on the "is_correct" field. It's identical to IsCorrectEQ.
func IsCorrect(v bool) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldEQ(FieldIsCorrect, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldEQ(FieldCreatedAt, v))
}

// ExamIDEQ applies the EQ predicate on the "exam_id" field.
func ExamIDEQ(v int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldEQ(FieldExamID, v))
}

// ExamIDNEQ applies the NEQ predicate on the "exam_id" field.
func ExamIDNEQ(v int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldNEQ(FieldExamID, v))
}

// ExamIDIn applies the In predicate on the "exam_id" field.
func ExamIDIn(vs ...int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldIn(FieldExamID, vs...))
}

// ExamIDNotIn applies the NotIn predicate on the "exam_id" field.
func ExamIDNotIn(vs ...int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldNotIn(FieldExamID, vs...))
}

// CorrectJpmIDEQ applies the EQ predicate on the "correct_jpm_id" field.
func CorrectJpmIDEQ(v int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldEQ(FieldCorrectJpmID, v))
}

// CorrectJpmIDNEQ applies the NEQ predicate on the "correct_jpm_id" field.
func CorrectJpmIDNEQ(v int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldNEQ(FieldCorrectJpmID, v))
}

// CorrectJpmIDIn applies the In predicate on the "correct_jpm_id" field.
func CorrectJpmIDIn(vs ...int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldIn(FieldCorrectJpmID, vs...))
}

// CorrectJpmIDNotIn applies the NotIn predicate on the "correct_jpm_id" field.
func CorrectJpmIDNotIn(vs ...int) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldNotIn(FieldCorrectJpmID, vs...))
}

// AnswerEQ applies the EQ predicate on the "answer" field.
func AnswerEQ(v string) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldEQ(FieldAnswer, v))
}

// AnswerNEQ applies the NEQ predicate on the "answer" field.
func AnswerNEQ(v string) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldNEQ(FieldAnswer, v))
}

// AnswerIn applies the In predicate on the "answer" field.
func AnswerIn(vs ...string) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldIn(FieldAnswer, vs...))
}

// AnswerNotIn applies the NotIn predicate on the "answer" field.
func AnswerNotIn(vs ...string) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldNotIn(FieldAnswer, vs...))
}

// AnswerGT applies the GT predicate on the "answer" field.
func AnswerGT(v string) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldGT(FieldAnswer, v))
}

// AnswerGTE applies the GTE predicate on the "answer" field.
func AnswerGTE(v string) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldGTE(FieldAnswer, v))
}

// AnswerLT applies the LT predicate on the "answer" field.
func AnswerLT(v string) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldLT(FieldAnswer, v))
}

// AnswerLTE applies the LTE predicate on the "answer" field.
func AnswerLTE(v string) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldLTE(FieldAnswer, v))
}

// AnswerContains applies the Contains predicate on the "answer" field.
func AnswerContains(v string) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldContains(FieldAnswer, v))
}

// AnswerHasPrefix applies the HasPrefix predicate on the "answer" field.
func AnswerHasPrefix(v string) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldHasPrefix(FieldAnswer, v))
}

// AnswerHasSuffix applies the HasSuffix predicate on the "answer" field.
func AnswerHasSuffix(v string) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldHasSuffix(FieldAnswer, v))
}

// AnswerEqualFold applies the EqualFold predicate on the "answer" field.
func AnswerEqualFold(v string) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldEqualFold(FieldAnswer, v))
}

// AnswerContainsFold applies the ContainsFold predicate on the "answer" field.
func AnswerContainsFold(v string) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldContainsFold(FieldAnswer, v))
}

// IsCorrectEQ applies the EQ predicate on the "is_correct" field.
func IsCorrectEQ(v bool) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldEQ(FieldIsCorrect, v))
}

// IsCorrectNEQ applies the NEQ predicate on the "is_correct" field.
func IsCorrectNEQ(v bool) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldNEQ(FieldIsCorrect, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.FieldLTE(FieldCreatedAt, v))
}

// HasExam applies the HasEdge predicate on the "exam" edge.
func HasExam() predicate.ExamQuestion {
	return predicate.ExamQuestion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ExamTable, ExamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExamWith applies the HasEdge predicate on the "exam" edge with a given conditions (other predicates).
func HasExamWith(preds ...predicate.Exam) predicate.ExamQuestion {
	return predicate.ExamQuestion(func(s *sql.Selector) {
		step := newExamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasJapaneseMean applies the HasEdge predicate on the "japanese_mean" edge.
func HasJapaneseMean() predicate.ExamQuestion {
	return predicate.ExamQuestion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, JapaneseMeanTable, JapaneseMeanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasJapaneseMeanWith applies the HasEdge predicate on the "japanese_mean" edge with a given conditions (other predicates).
func HasJapaneseMeanWith(preds ...predicate.JapaneseMean) predicate.ExamQuestion {
	return predicate.ExamQuestion(func(s *sql.Selector) {
		step := newJapaneseMeanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExamQuestion) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExamQuestion) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExamQuestion) predicate.ExamQuestion {
	return predicate.ExamQuestion(sql.NotPredicates(p))
}
