// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"context"
	"word_app/backend/src/interfaces/http/user"
	"word_app/backend/src/models"

	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// DeleteHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) DeleteHandler() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteHandler")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_DeleteHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteHandler'
type MockHandler_DeleteHandler_Call struct {
	*mock.Call
}

// DeleteHandler is a helper method to define mock.On call
func (_e *MockHandler_Expecter) DeleteHandler() *MockHandler_DeleteHandler_Call {
	return &MockHandler_DeleteHandler_Call{Call: _e.mock.On("DeleteHandler")}
}

func (_c *MockHandler_DeleteHandler_Call) Run(run func()) *MockHandler_DeleteHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_DeleteHandler_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_DeleteHandler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_DeleteHandler_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_DeleteHandler_Call {
	_c.Call.Return(run)
	return _c
}

// EditHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) EditHandler() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EditHandler")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_EditHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditHandler'
type MockHandler_EditHandler_Call struct {
	*mock.Call
}

// EditHandler is a helper method to define mock.On call
func (_e *MockHandler_Expecter) EditHandler() *MockHandler_EditHandler_Call {
	return &MockHandler_EditHandler_Call{Call: _e.mock.On("EditHandler")}
}

func (_c *MockHandler_EditHandler_Call) Run(run func()) *MockHandler_EditHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_EditHandler_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_EditHandler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_EditHandler_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_EditHandler_Call {
	_c.Call.Return(run)
	return _c
}

// ListHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) ListHandler() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListHandler")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_ListHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHandler'
type MockHandler_ListHandler_Call struct {
	*mock.Call
}

// ListHandler is a helper method to define mock.On call
func (_e *MockHandler_Expecter) ListHandler() *MockHandler_ListHandler_Call {
	return &MockHandler_ListHandler_Call{Call: _e.mock.On("ListHandler")}
}

func (_c *MockHandler_ListHandler_Call) Run(run func()) *MockHandler_ListHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_ListHandler_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_ListHandler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_ListHandler_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_ListHandler_Call {
	_c.Call.Return(run)
	return _c
}

// MeHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) MeHandler() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MeHandler")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_MeHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MeHandler'
type MockHandler_MeHandler_Call struct {
	*mock.Call
}

// MeHandler is a helper method to define mock.On call
func (_e *MockHandler_Expecter) MeHandler() *MockHandler_MeHandler_Call {
	return &MockHandler_MeHandler_Call{Call: _e.mock.On("MeHandler")}
}

func (_c *MockHandler_MeHandler_Call) Run(run func()) *MockHandler_MeHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_MeHandler_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_MeHandler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_MeHandler_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_MeHandler_Call {
	_c.Call.Return(run)
	return _c
}

// MyPageHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) MyPageHandler() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MyPageHandler")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_MyPageHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MyPageHandler'
type MockHandler_MyPageHandler_Call struct {
	*mock.Call
}

// MyPageHandler is a helper method to define mock.On call
func (_e *MockHandler_Expecter) MyPageHandler() *MockHandler_MyPageHandler_Call {
	return &MockHandler_MyPageHandler_Call{Call: _e.mock.On("MyPageHandler")}
}

func (_c *MockHandler_MyPageHandler_Call) Run(run func()) *MockHandler_MyPageHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_MyPageHandler_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_MyPageHandler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_MyPageHandler_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_MyPageHandler_Call {
	_c.Call.Return(run)
	return _c
}

// ShowHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) ShowHandler() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShowHandler")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_ShowHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowHandler'
type MockHandler_ShowHandler_Call struct {
	*mock.Call
}

// ShowHandler is a helper method to define mock.On call
func (_e *MockHandler_Expecter) ShowHandler() *MockHandler_ShowHandler_Call {
	return &MockHandler_ShowHandler_Call{Call: _e.mock.On("ShowHandler")}
}

func (_c *MockHandler_ShowHandler_Call) Run(run func()) *MockHandler_ShowHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_ShowHandler_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_ShowHandler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_ShowHandler_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_ShowHandler_Call {
	_c.Call.Return(run)
	return _c
}

// SignInHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) SignInHandler() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SignInHandler")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_SignInHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignInHandler'
type MockHandler_SignInHandler_Call struct {
	*mock.Call
}

// SignInHandler is a helper method to define mock.On call
func (_e *MockHandler_Expecter) SignInHandler() *MockHandler_SignInHandler_Call {
	return &MockHandler_SignInHandler_Call{Call: _e.mock.On("SignInHandler")}
}

func (_c *MockHandler_SignInHandler_Call) Run(run func()) *MockHandler_SignInHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_SignInHandler_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_SignInHandler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_SignInHandler_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_SignInHandler_Call {
	_c.Call.Return(run)
	return _c
}

// SignUpHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) SignUpHandler() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SignUpHandler")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_SignUpHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUpHandler'
type MockHandler_SignUpHandler_Call struct {
	*mock.Call
}

// SignUpHandler is a helper method to define mock.On call
func (_e *MockHandler_Expecter) SignUpHandler() *MockHandler_SignUpHandler_Call {
	return &MockHandler_SignUpHandler_Call{Call: _e.mock.On("SignUpHandler")}
}

func (_c *MockHandler_SignUpHandler_Call) Run(run func()) *MockHandler_SignUpHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_SignUpHandler_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_SignUpHandler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_SignUpHandler_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_SignUpHandler_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecase creates a new instance of MockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecase {
	mock := &MockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

type MockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecase) EXPECT() *MockUsecase_Expecter {
	return &MockUsecase_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockUsecase
func (_mock *MockUsecase) Delete(ctx context.Context, in user.DeleteUserInput) error {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.DeleteUserInput) error); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - in user.DeleteUserInput
func (_e *MockUsecase_Expecter) Delete(ctx interface{}, in interface{}) *MockUsecase_Delete_Call {
	return &MockUsecase_Delete_Call{Call: _e.mock.On("Delete", ctx, in)}
}

func (_c *MockUsecase_Delete_Call) Run(run func(ctx context.Context, in user.DeleteUserInput)) *MockUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.DeleteUserInput
		if args[1] != nil {
			arg1 = args[1].(user.DeleteUserInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_Delete_Call) Return(err error) *MockUsecase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsecase_Delete_Call) RunAndReturn(run func(ctx context.Context, in user.DeleteUserInput) error) *MockUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockUsecase
func (_mock *MockUsecase) FindByEmail(ctx context.Context, email string) (*user.FindByEmailOutput, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *user.FindByEmailOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.FindByEmailOutput, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.FindByEmailOutput); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.FindByEmailOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUsecase_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUsecase_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockUsecase_FindByEmail_Call {
	return &MockUsecase_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockUsecase_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUsecase_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_FindByEmail_Call) Return(findByEmailOutput *user.FindByEmailOutput, err error) *MockUsecase_FindByEmail_Call {
	_c.Call.Return(findByEmailOutput, err)
	return _c
}

func (_c *MockUsecase_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*user.FindByEmailOutput, error)) *MockUsecase_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetDetailByID provides a mock function for the type MockUsecase
func (_mock *MockUsecase) GetDetailByID(ctx context.Context, viewerID int, targetID int) (*models.UserDetail, error) {
	ret := _mock.Called(ctx, viewerID, targetID)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailByID")
	}

	var r0 *models.UserDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (*models.UserDetail, error)); ok {
		return returnFunc(ctx, viewerID, targetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) *models.UserDetail); ok {
		r0 = returnFunc(ctx, viewerID, targetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, viewerID, targetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_GetDetailByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetailByID'
type MockUsecase_GetDetailByID_Call struct {
	*mock.Call
}

// GetDetailByID is a helper method to define mock.On call
//   - ctx context.Context
//   - viewerID int
//   - targetID int
func (_e *MockUsecase_Expecter) GetDetailByID(ctx interface{}, viewerID interface{}, targetID interface{}) *MockUsecase_GetDetailByID_Call {
	return &MockUsecase_GetDetailByID_Call{Call: _e.mock.On("GetDetailByID", ctx, viewerID, targetID)}
}

func (_c *MockUsecase_GetDetailByID_Call) Run(run func(ctx context.Context, viewerID int, targetID int)) *MockUsecase_GetDetailByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsecase_GetDetailByID_Call) Return(userDetail *models.UserDetail, err error) *MockUsecase_GetDetailByID_Call {
	_c.Call.Return(userDetail, err)
	return _c
}

func (_c *MockUsecase_GetDetailByID_Call) RunAndReturn(run func(ctx context.Context, viewerID int, targetID int) (*models.UserDetail, error)) *MockUsecase_GetDetailByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMyDetail provides a mock function for the type MockUsecase
func (_mock *MockUsecase) GetMyDetail(ctx context.Context, viewerID int) (*models.UserDetail, error) {
	ret := _mock.Called(ctx, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetMyDetail")
	}

	var r0 *models.UserDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.UserDetail, error)); ok {
		return returnFunc(ctx, viewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.UserDetail); ok {
		r0 = returnFunc(ctx, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, viewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_GetMyDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMyDetail'
type MockUsecase_GetMyDetail_Call struct {
	*mock.Call
}

// GetMyDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - viewerID int
func (_e *MockUsecase_Expecter) GetMyDetail(ctx interface{}, viewerID interface{}) *MockUsecase_GetMyDetail_Call {
	return &MockUsecase_GetMyDetail_Call{Call: _e.mock.On("GetMyDetail", ctx, viewerID)}
}

func (_c *MockUsecase_GetMyDetail_Call) Run(run func(ctx context.Context, viewerID int)) *MockUsecase_GetMyDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_GetMyDetail_Call) Return(userDetail *models.UserDetail, err error) *MockUsecase_GetMyDetail_Call {
	_c.Call.Return(userDetail, err)
	return _c
}

func (_c *MockUsecase_GetMyDetail_Call) RunAndReturn(run func(ctx context.Context, viewerID int) (*models.UserDetail, error)) *MockUsecase_GetMyDetail_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function for the type MockUsecase
func (_mock *MockUsecase) ListUsers(ctx context.Context, in user.ListUsersInput) (*user.UserListResponse, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 *user.UserListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.ListUsersInput) (*user.UserListResponse, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.ListUsersInput) *user.UserListResponse); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.ListUsersInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUsecase_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - in user.ListUsersInput
func (_e *MockUsecase_Expecter) ListUsers(ctx interface{}, in interface{}) *MockUsecase_ListUsers_Call {
	return &MockUsecase_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, in)}
}

func (_c *MockUsecase_ListUsers_Call) Run(run func(ctx context.Context, in user.ListUsersInput)) *MockUsecase_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.ListUsersInput
		if args[1] != nil {
			arg1 = args[1].(user.ListUsersInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_ListUsers_Call) Return(userListResponse *user.UserListResponse, err error) *MockUsecase_ListUsers_Call {
	_c.Call.Return(userListResponse, err)
	return _c
}

func (_c *MockUsecase_ListUsers_Call) RunAndReturn(run func(ctx context.Context, in user.ListUsersInput) (*user.UserListResponse, error)) *MockUsecase_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// SignUp provides a mock function for the type MockUsecase
func (_mock *MockUsecase) SignUp(ctx context.Context, in user.SignUpInput) (*user.SignUpOutput, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 *user.SignUpOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.SignUpInput) (*user.SignUpOutput, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.SignUpInput) *user.SignUpOutput); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.SignUpOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.SignUpInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type MockUsecase_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - ctx context.Context
//   - in user.SignUpInput
func (_e *MockUsecase_Expecter) SignUp(ctx interface{}, in interface{}) *MockUsecase_SignUp_Call {
	return &MockUsecase_SignUp_Call{Call: _e.mock.On("SignUp", ctx, in)}
}

func (_c *MockUsecase_SignUp_Call) Run(run func(ctx context.Context, in user.SignUpInput)) *MockUsecase_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.SignUpInput
		if args[1] != nil {
			arg1 = args[1].(user.SignUpInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_SignUp_Call) Return(signUpOutput *user.SignUpOutput, err error) *MockUsecase_SignUp_Call {
	_c.Call.Return(signUpOutput, err)
	return _c
}

func (_c *MockUsecase_SignUp_Call) RunAndReturn(run func(ctx context.Context, in user.SignUpInput) (*user.SignUpOutput, error)) *MockUsecase_SignUp_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUsecase
func (_mock *MockUsecase) UpdateUser(ctx context.Context, in user.UpdateUserInput) (*models.UserDetail, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *models.UserDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.UpdateUserInput) (*models.UserDetail, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.UpdateUserInput) *models.UserDetail); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.UpdateUserInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUsecase_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - in user.UpdateUserInput
func (_e *MockUsecase_Expecter) UpdateUser(ctx interface{}, in interface{}) *MockUsecase_UpdateUser_Call {
	return &MockUsecase_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, in)}
}

func (_c *MockUsecase_UpdateUser_Call) Run(run func(ctx context.Context, in user.UpdateUserInput)) *MockUsecase_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.UpdateUserInput
		if args[1] != nil {
			arg1 = args[1].(user.UpdateUserInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_UpdateUser_Call) Return(userDetail *models.UserDetail, err error) *MockUsecase_UpdateUser_Call {
	_c.Call.Return(userDetail, err)
	return _c
}

func (_c *MockUsecase_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, in user.UpdateUserInput) (*models.UserDetail, error)) *MockUsecase_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
