// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"context"
	"word_app/backend/ent"
	"word_app/backend/src/models"

	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// DeleteHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) DeleteHandler() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteHandler")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_DeleteHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteHandler'
type MockHandler_DeleteHandler_Call struct {
	*mock.Call
}

// DeleteHandler is a helper method to define mock.On call
func (_e *MockHandler_Expecter) DeleteHandler() *MockHandler_DeleteHandler_Call {
	return &MockHandler_DeleteHandler_Call{Call: _e.mock.On("DeleteHandler")}
}

func (_c *MockHandler_DeleteHandler_Call) Run(run func()) *MockHandler_DeleteHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_DeleteHandler_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_DeleteHandler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_DeleteHandler_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_DeleteHandler_Call {
	_c.Call.Return(run)
	return _c
}

// EditHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) EditHandler() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EditHandler")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_EditHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditHandler'
type MockHandler_EditHandler_Call struct {
	*mock.Call
}

// EditHandler is a helper method to define mock.On call
func (_e *MockHandler_Expecter) EditHandler() *MockHandler_EditHandler_Call {
	return &MockHandler_EditHandler_Call{Call: _e.mock.On("EditHandler")}
}

func (_c *MockHandler_EditHandler_Call) Run(run func()) *MockHandler_EditHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_EditHandler_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_EditHandler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_EditHandler_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_EditHandler_Call {
	_c.Call.Return(run)
	return _c
}

// ListHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) ListHandler() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListHandler")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_ListHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHandler'
type MockHandler_ListHandler_Call struct {
	*mock.Call
}

// ListHandler is a helper method to define mock.On call
func (_e *MockHandler_Expecter) ListHandler() *MockHandler_ListHandler_Call {
	return &MockHandler_ListHandler_Call{Call: _e.mock.On("ListHandler")}
}

func (_c *MockHandler_ListHandler_Call) Run(run func()) *MockHandler_ListHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_ListHandler_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_ListHandler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_ListHandler_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_ListHandler_Call {
	_c.Call.Return(run)
	return _c
}

// MyPageHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) MyPageHandler() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MyPageHandler")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_MyPageHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MyPageHandler'
type MockHandler_MyPageHandler_Call struct {
	*mock.Call
}

// MyPageHandler is a helper method to define mock.On call
func (_e *MockHandler_Expecter) MyPageHandler() *MockHandler_MyPageHandler_Call {
	return &MockHandler_MyPageHandler_Call{Call: _e.mock.On("MyPageHandler")}
}

func (_c *MockHandler_MyPageHandler_Call) Run(run func()) *MockHandler_MyPageHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_MyPageHandler_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_MyPageHandler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_MyPageHandler_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_MyPageHandler_Call {
	_c.Call.Return(run)
	return _c
}

// SignInHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) SignInHandler() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SignInHandler")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_SignInHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignInHandler'
type MockHandler_SignInHandler_Call struct {
	*mock.Call
}

// SignInHandler is a helper method to define mock.On call
func (_e *MockHandler_Expecter) SignInHandler() *MockHandler_SignInHandler_Call {
	return &MockHandler_SignInHandler_Call{Call: _e.mock.On("SignInHandler")}
}

func (_c *MockHandler_SignInHandler_Call) Run(run func()) *MockHandler_SignInHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_SignInHandler_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_SignInHandler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_SignInHandler_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_SignInHandler_Call {
	_c.Call.Return(run)
	return _c
}

// SignUpHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) SignUpHandler() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SignUpHandler")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_SignUpHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUpHandler'
type MockHandler_SignUpHandler_Call struct {
	*mock.Call
}

// SignUpHandler is a helper method to define mock.On call
func (_e *MockHandler_Expecter) SignUpHandler() *MockHandler_SignUpHandler_Call {
	return &MockHandler_SignUpHandler_Call{Call: _e.mock.On("SignUpHandler")}
}

func (_c *MockHandler_SignUpHandler_Call) Run(run func()) *MockHandler_SignUpHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_SignUpHandler_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_SignUpHandler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_SignUpHandler_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_SignUpHandler_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDetailHandler creates a new instance of MockDetailHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDetailHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDetailHandler {
	mock := &MockDetailHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDetailHandler is an autogenerated mock type for the DetailHandler type
type MockDetailHandler struct {
	mock.Mock
}

type MockDetailHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDetailHandler) EXPECT() *MockDetailHandler_Expecter {
	return &MockDetailHandler_Expecter{mock: &_m.Mock}
}

// MeHandler provides a mock function for the type MockDetailHandler
func (_mock *MockDetailHandler) MeHandler() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MeHandler")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockDetailHandler_MeHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MeHandler'
type MockDetailHandler_MeHandler_Call struct {
	*mock.Call
}

// MeHandler is a helper method to define mock.On call
func (_e *MockDetailHandler_Expecter) MeHandler() *MockDetailHandler_MeHandler_Call {
	return &MockDetailHandler_MeHandler_Call{Call: _e.mock.On("MeHandler")}
}

func (_c *MockDetailHandler_MeHandler_Call) Run(run func()) *MockDetailHandler_MeHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDetailHandler_MeHandler_Call) Return(handlerFunc gin.HandlerFunc) *MockDetailHandler_MeHandler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockDetailHandler_MeHandler_Call) RunAndReturn(run func() gin.HandlerFunc) *MockDetailHandler_MeHandler_Call {
	_c.Call.Return(run)
	return _c
}

// ShowHandler provides a mock function for the type MockDetailHandler
func (_mock *MockDetailHandler) ShowHandler() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShowHandler")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockDetailHandler_ShowHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowHandler'
type MockDetailHandler_ShowHandler_Call struct {
	*mock.Call
}

// ShowHandler is a helper method to define mock.On call
func (_e *MockDetailHandler_Expecter) ShowHandler() *MockDetailHandler_ShowHandler_Call {
	return &MockDetailHandler_ShowHandler_Call{Call: _e.mock.On("ShowHandler")}
}

func (_c *MockDetailHandler_ShowHandler_Call) Run(run func()) *MockDetailHandler_ShowHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDetailHandler_ShowHandler_Call) Return(handlerFunc gin.HandlerFunc) *MockDetailHandler_ShowHandler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockDetailHandler_ShowHandler_Call) RunAndReturn(run func() gin.HandlerFunc) *MockDetailHandler_ShowHandler_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockClient
func (_mock *MockClient) Create(ctx context.Context, email string, name string, password string) (*ent.User, error) {
	ret := _mock.Called(ctx, email, name, password)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *ent.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*ent.User, error)); ok {
		return returnFunc(ctx, email, name, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *ent.User); ok {
		r0 = returnFunc(ctx, email, name, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, email, name, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - name string
//   - password string
func (_e *MockClient_Expecter) Create(ctx interface{}, email interface{}, name interface{}, password interface{}) *MockClient_Create_Call {
	return &MockClient_Create_Call{Call: _e.mock.On("Create", ctx, email, name, password)}
}

func (_c *MockClient_Create_Call) Run(run func(ctx context.Context, email string, name string, password string)) *MockClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_Create_Call) Return(user *ent.User, err error) *MockClient_Create_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockClient_Create_Call) RunAndReturn(run func(ctx context.Context, email string, name string, password string) (*ent.User, error)) *MockClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockClient
func (_mock *MockClient) Delete(ctx context.Context, editorID int, targetID int) error {
	ret := _mock.Called(ctx, editorID, targetID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, editorID, targetID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - editorID int
//   - targetID int
func (_e *MockClient_Expecter) Delete(ctx interface{}, editorID interface{}, targetID interface{}) *MockClient_Delete_Call {
	return &MockClient_Delete_Call{Call: _e.mock.On("Delete", ctx, editorID, targetID)}
}

func (_c *MockClient_Delete_Call) Run(run func(ctx context.Context, editorID int, targetID int)) *MockClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_Delete_Call) Return(err error) *MockClient_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Delete_Call) RunAndReturn(run func(ctx context.Context, editorID int, targetID int) error) *MockClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockClient
func (_mock *MockClient) FindByEmail(ctx context.Context, email string) (*ent.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *ent.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ent.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ent.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockClient_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockClient_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockClient_FindByEmail_Call {
	return &MockClient_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockClient_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockClient_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_FindByEmail_Call) Return(user *ent.User, err error) *MockClient_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockClient_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*ent.User, error)) *MockClient_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockClient
func (_mock *MockClient) FindByID(ctx context.Context, id int) (*ent.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *ent.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*ent.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *ent.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockClient_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockClient_Expecter) FindByID(ctx interface{}, id interface{}) *MockClient_FindByID_Call {
	return &MockClient_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockClient_FindByID_Call) Run(run func(ctx context.Context, id int)) *MockClient_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_FindByID_Call) Return(user *ent.User, err error) *MockClient_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockClient_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*ent.User, error)) *MockClient_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockClient
func (_mock *MockClient) GetUsers(ctx context.Context, UserListRequest *models.UserListRequest) (*models.UserListResponse, error) {
	ret := _mock.Called(ctx, UserListRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 *models.UserListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.UserListRequest) (*models.UserListResponse, error)); ok {
		return returnFunc(ctx, UserListRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.UserListRequest) *models.UserListResponse); ok {
		r0 = returnFunc(ctx, UserListRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.UserListRequest) error); ok {
		r1 = returnFunc(ctx, UserListRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockClient_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - UserListRequest *models.UserListRequest
func (_e *MockClient_Expecter) GetUsers(ctx interface{}, UserListRequest interface{}) *MockClient_GetUsers_Call {
	return &MockClient_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, UserListRequest)}
}

func (_c *MockClient_GetUsers_Call) Run(run func(ctx context.Context, UserListRequest *models.UserListRequest)) *MockClient_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.UserListRequest
		if args[1] != nil {
			arg1 = args[1].(*models.UserListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetUsers_Call) Return(userListResponse *models.UserListResponse, err error) *MockClient_GetUsers_Call {
	_c.Call.Return(userListResponse, err)
	return _c
}

func (_c *MockClient_GetUsers_Call) RunAndReturn(run func(ctx context.Context, UserListRequest *models.UserListRequest) (*models.UserListResponse, error)) *MockClient_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockClient
func (_mock *MockClient) Update(ctx context.Context, UserEditRequest *models.UpdateUserInput) (*ent.User, error) {
	ret := _mock.Called(ctx, UserEditRequest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *ent.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.UpdateUserInput) (*ent.User, error)); ok {
		return returnFunc(ctx, UserEditRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.UpdateUserInput) *ent.User); ok {
		r0 = returnFunc(ctx, UserEditRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.UpdateUserInput) error); ok {
		r1 = returnFunc(ctx, UserEditRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - UserEditRequest *models.UpdateUserInput
func (_e *MockClient_Expecter) Update(ctx interface{}, UserEditRequest interface{}) *MockClient_Update_Call {
	return &MockClient_Update_Call{Call: _e.mock.On("Update", ctx, UserEditRequest)}
}

func (_c *MockClient_Update_Call) Run(run func(ctx context.Context, UserEditRequest *models.UpdateUserInput)) *MockClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.UpdateUserInput
		if args[1] != nil {
			arg1 = args[1].(*models.UpdateUserInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_Update_Call) Return(user *ent.User, err error) *MockClient_Update_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockClient_Update_Call) RunAndReturn(run func(ctx context.Context, UserEditRequest *models.UpdateUserInput) (*ent.User, error)) *MockClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecase creates a new instance of MockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecase {
	mock := &MockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

type MockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecase) EXPECT() *MockUsecase_Expecter {
	return &MockUsecase_Expecter{mock: &_m.Mock}
}

// GetDetailByID provides a mock function for the type MockUsecase
func (_mock *MockUsecase) GetDetailByID(ctx context.Context, viewerID int, targetID int) (*models.UserDetail, error) {
	ret := _mock.Called(ctx, viewerID, targetID)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailByID")
	}

	var r0 *models.UserDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (*models.UserDetail, error)); ok {
		return returnFunc(ctx, viewerID, targetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) *models.UserDetail); ok {
		r0 = returnFunc(ctx, viewerID, targetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, viewerID, targetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_GetDetailByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetailByID'
type MockUsecase_GetDetailByID_Call struct {
	*mock.Call
}

// GetDetailByID is a helper method to define mock.On call
//   - ctx context.Context
//   - viewerID int
//   - targetID int
func (_e *MockUsecase_Expecter) GetDetailByID(ctx interface{}, viewerID interface{}, targetID interface{}) *MockUsecase_GetDetailByID_Call {
	return &MockUsecase_GetDetailByID_Call{Call: _e.mock.On("GetDetailByID", ctx, viewerID, targetID)}
}

func (_c *MockUsecase_GetDetailByID_Call) Run(run func(ctx context.Context, viewerID int, targetID int)) *MockUsecase_GetDetailByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsecase_GetDetailByID_Call) Return(userDetail *models.UserDetail, err error) *MockUsecase_GetDetailByID_Call {
	_c.Call.Return(userDetail, err)
	return _c
}

func (_c *MockUsecase_GetDetailByID_Call) RunAndReturn(run func(ctx context.Context, viewerID int, targetID int) (*models.UserDetail, error)) *MockUsecase_GetDetailByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMyDetail provides a mock function for the type MockUsecase
func (_mock *MockUsecase) GetMyDetail(ctx context.Context, viewerID int) (*models.UserDetail, error) {
	ret := _mock.Called(ctx, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetMyDetail")
	}

	var r0 *models.UserDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.UserDetail, error)); ok {
		return returnFunc(ctx, viewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.UserDetail); ok {
		r0 = returnFunc(ctx, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, viewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_GetMyDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMyDetail'
type MockUsecase_GetMyDetail_Call struct {
	*mock.Call
}

// GetMyDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - viewerID int
func (_e *MockUsecase_Expecter) GetMyDetail(ctx interface{}, viewerID interface{}) *MockUsecase_GetMyDetail_Call {
	return &MockUsecase_GetMyDetail_Call{Call: _e.mock.On("GetMyDetail", ctx, viewerID)}
}

func (_c *MockUsecase_GetMyDetail_Call) Run(run func(ctx context.Context, viewerID int)) *MockUsecase_GetMyDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_GetMyDetail_Call) Return(userDetail *models.UserDetail, err error) *MockUsecase_GetMyDetail_Call {
	_c.Call.Return(userDetail, err)
	return _c
}

func (_c *MockUsecase_GetMyDetail_Call) RunAndReturn(run func(ctx context.Context, viewerID int) (*models.UserDetail, error)) *MockUsecase_GetMyDetail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// SignIn provides a mock function for the type MockValidator
func (_mock *MockValidator) SignIn(SignInRequest *models.SignInRequest) []*models.FieldError {
	ret := _mock.Called(SignInRequest)

	if len(ret) == 0 {
		panic("no return value specified for SignIn")
	}

	var r0 []*models.FieldError
	if returnFunc, ok := ret.Get(0).(func(*models.SignInRequest) []*models.FieldError); ok {
		r0 = returnFunc(SignInRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.FieldError)
		}
	}
	return r0
}

// MockValidator_SignIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignIn'
type MockValidator_SignIn_Call struct {
	*mock.Call
}

// SignIn is a helper method to define mock.On call
//   - SignInRequest *models.SignInRequest
func (_e *MockValidator_Expecter) SignIn(SignInRequest interface{}) *MockValidator_SignIn_Call {
	return &MockValidator_SignIn_Call{Call: _e.mock.On("SignIn", SignInRequest)}
}

func (_c *MockValidator_SignIn_Call) Run(run func(SignInRequest *models.SignInRequest)) *MockValidator_SignIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.SignInRequest
		if args[0] != nil {
			arg0 = args[0].(*models.SignInRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockValidator_SignIn_Call) Return(fieldErrors []*models.FieldError) *MockValidator_SignIn_Call {
	_c.Call.Return(fieldErrors)
	return _c
}

func (_c *MockValidator_SignIn_Call) RunAndReturn(run func(SignInRequest *models.SignInRequest) []*models.FieldError) *MockValidator_SignIn_Call {
	_c.Call.Return(run)
	return _c
}

// SignUp provides a mock function for the type MockValidator
func (_mock *MockValidator) SignUp(SignUpRequest *models.SignUpRequest) []*models.FieldError {
	ret := _mock.Called(SignUpRequest)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 []*models.FieldError
	if returnFunc, ok := ret.Get(0).(func(*models.SignUpRequest) []*models.FieldError); ok {
		r0 = returnFunc(SignUpRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.FieldError)
		}
	}
	return r0
}

// MockValidator_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type MockValidator_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - SignUpRequest *models.SignUpRequest
func (_e *MockValidator_Expecter) SignUp(SignUpRequest interface{}) *MockValidator_SignUp_Call {
	return &MockValidator_SignUp_Call{Call: _e.mock.On("SignUp", SignUpRequest)}
}

func (_c *MockValidator_SignUp_Call) Run(run func(SignUpRequest *models.SignUpRequest)) *MockValidator_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.SignUpRequest
		if args[0] != nil {
			arg0 = args[0].(*models.SignUpRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockValidator_SignUp_Call) Return(fieldErrors []*models.FieldError) *MockValidator_SignUp_Call {
	_c.Call.Return(fieldErrors)
	return _c
}

func (_c *MockValidator_SignUp_Call) RunAndReturn(run func(SignUpRequest *models.SignUpRequest) []*models.FieldError) *MockValidator_SignUp_Call {
	_c.Call.Return(run)
	return _c
}
