// Code generated by ent, DO NOT EDIT.

package japanesemean

import (
	"time"
	"word_app/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldEQ(FieldName, v))
}

// WordInfoID applies equality check predicate on the "word_info_id" field. It's identical to WordInfoIDEQ.
func WordInfoID(v int) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldEQ(FieldWordInfoID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldContainsFold(FieldName, v))
}

// WordInfoIDEQ applies the EQ predicate on the "word_info_id" field.
func WordInfoIDEQ(v int) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldEQ(FieldWordInfoID, v))
}

// WordInfoIDNEQ applies the NEQ predicate on the "word_info_id" field.
func WordInfoIDNEQ(v int) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldNEQ(FieldWordInfoID, v))
}

// WordInfoIDIn applies the In predicate on the "word_info_id" field.
func WordInfoIDIn(vs ...int) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldIn(FieldWordInfoID, vs...))
}

// WordInfoIDNotIn applies the NotIn predicate on the "word_info_id" field.
func WordInfoIDNotIn(vs ...int) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldNotIn(FieldWordInfoID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasWordInfo applies the HasEdge predicate on the "word_info" edge.
func HasWordInfo() predicate.JapaneseMean {
	return predicate.JapaneseMean(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WordInfoTable, WordInfoColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWordInfoWith applies the HasEdge predicate on the "word_info" edge with a given conditions (other predicates).
func HasWordInfoWith(preds ...predicate.WordInfo) predicate.JapaneseMean {
	return predicate.JapaneseMean(func(s *sql.Selector) {
		step := newWordInfoStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasExamQuestions applies the HasEdge predicate on the "exam_questions" edge.
func HasExamQuestions() predicate.JapaneseMean {
	return predicate.JapaneseMean(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ExamQuestionsTable, ExamQuestionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExamQuestionsWith applies the HasEdge predicate on the "exam_questions" edge with a given conditions (other predicates).
func HasExamQuestionsWith(preds ...predicate.ExamQuestion) predicate.JapaneseMean {
	return predicate.JapaneseMean(func(s *sql.Selector) {
		step := newExamQuestionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.JapaneseMean) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.JapaneseMean) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.JapaneseMean) predicate.JapaneseMean {
	return predicate.JapaneseMean(sql.NotPredicates(p))
}
